# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '2dgui.ui'
#
# Created: Thu May 23 11:57:09 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from mymplcanvas import MyMplCanvas

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1255, 809)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 281, 201))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setStyleSheet(_fromUtf8(""))
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.phaseOffsetLabel = QtGui.QLabel(self.groupBox)
        self.phaseOffsetLabel.setObjectName(_fromUtf8("phaseOffsetLabel"))
        self.gridLayout.addWidget(self.phaseOffsetLabel, 1, 0, 1, 1)
        self.isLambda2PlateCheckBox = QtGui.QCheckBox(self.groupBox)
        self.isLambda2PlateCheckBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.isLambda2PlateCheckBox.setChecked(True)
        self.isLambda2PlateCheckBox.setObjectName(_fromUtf8("isLambda2PlateCheckBox"))
        self.gridLayout.addWidget(self.isLambda2PlateCheckBox, 2, 1, 1, 1)
        self.phaseOffsetLineEdit = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phaseOffsetLineEdit.sizePolicy().hasHeightForWidth())
        self.phaseOffsetLineEdit.setSizePolicy(sizePolicy)
        self.phaseOffsetLineEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.phaseOffsetLineEdit.setObjectName(_fromUtf8("phaseOffsetLineEdit"))
        self.gridLayout.addWidget(self.phaseOffsetLineEdit, 1, 1, 1, 1)
        self.isLambda2PlateLabel = QtGui.QLabel(self.groupBox)
        self.isLambda2PlateLabel.setObjectName(_fromUtf8("isLambda2PlateLabel"))
        self.gridLayout.addWidget(self.isLambda2PlateLabel, 2, 0, 1, 1)
        self.whichSetupComboBox = QtGui.QComboBox(self.groupBox)
        self.whichSetupComboBox.setObjectName(_fromUtf8("whichSetupComboBox"))
        self.whichSetupComboBox.addItem(_fromUtf8(""))
        self.whichSetupComboBox.addItem(_fromUtf8(""))
        self.whichSetupComboBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.whichSetupComboBox, 0, 0, 1, 2)
        self.selectDataDirPushButton = QtGui.QPushButton(self.groupBox)
        self.selectDataDirPushButton.setMinimumSize(QtCore.QSize(101, 27))
        self.selectDataDirPushButton.setObjectName(_fromUtf8("selectDataDirPushButton"))
        self.gridLayout.addWidget(self.selectDataDirPushButton, 3, 0, 1, 2)
        self.selectSPEComboBox = QtGui.QComboBox(self.groupBox)
        self.selectSPEComboBox.setObjectName(_fromUtf8("selectSPEComboBox"))
        self.gridLayout.addWidget(self.selectSPEComboBox, 4, 0, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout)
        self.imageview = MyMplCanvas(self.centralwidget, width=2, height=2, dpi=100)
        self.imageview.setGeometry(QtCore.QRect(30, 250, 581, 491))
        self.imageview.setFocusPolicy(QtCore.Qt.NoFocus)
        self.imageview.setObjectName(_fromUtf8("imageview"))
        self.dataview = MyMplCanvas(self.centralwidget, width=2, height=2, dpi=100)
        self.dataview.setGeometry(QtCore.QRect(640, 250, 581, 491))
        self.dataview.setObjectName(_fromUtf8("dataview"))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(300, 10, 221, 201))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setStyleSheet(_fromUtf8(""))
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setContentsMargins(8, -1, 8, -1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.spotEdgeLengthSpinBox = QtGui.QSpinBox(self.groupBox_2)
        self.spotEdgeLengthSpinBox.setProperty("value", 20)
        self.spotEdgeLengthSpinBox.setObjectName(_fromUtf8("spotEdgeLengthSpinBox"))
        self.gridLayout_2.addWidget(self.spotEdgeLengthSpinBox, 5, 2, 1, 1)
        self.phaseOffsetLabel_2 = QtGui.QLabel(self.groupBox_2)
        self.phaseOffsetLabel_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.phaseOffsetLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.phaseOffsetLabel_2.setObjectName(_fromUtf8("phaseOffsetLabel_2"))
        self.gridLayout_2.addWidget(self.phaseOffsetLabel_2, 5, 1, 1, 1)
        self.createSpotArrayPushButton = QtGui.QPushButton(self.groupBox_2)
        self.createSpotArrayPushButton.setMinimumSize(QtCore.QSize(101, 27))
        self.createSpotArrayPushButton.setObjectName(_fromUtf8("createSpotArrayPushButton"))
        self.gridLayout_2.addWidget(self.createSpotArrayPushButton, 6, 1, 1, 2)
        self.clearAllSpotsPushButton = QtGui.QPushButton(self.groupBox_2)
        self.clearAllSpotsPushButton.setMinimumSize(QtCore.QSize(101, 27))
        self.clearAllSpotsPushButton.setObjectName(_fromUtf8("clearAllSpotsPushButton"))
        self.gridLayout_2.addWidget(self.clearAllSpotsPushButton, 7, 1, 1, 1)
        self.setBGSpotPushButton = QtGui.QPushButton(self.groupBox_2)
        self.setBGSpotPushButton.setMinimumSize(QtCore.QSize(101, 27))
        self.setBGSpotPushButton.setObjectName(_fromUtf8("setBGSpotPushButton"))
        self.gridLayout_2.addWidget(self.setBGSpotPushButton, 2, 1, 1, 2)
        self.addSignalSpotPushButton = QtGui.QPushButton(self.groupBox_2)
        self.addSignalSpotPushButton.setMinimumSize(QtCore.QSize(101, 27))
        self.addSignalSpotPushButton.setObjectName(_fromUtf8("addSignalSpotPushButton"))
        self.gridLayout_2.addWidget(self.addSignalSpotPushButton, 3, 1, 1, 2)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(530, 10, 351, 201))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setStyleSheet(_fromUtf8(""))
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setCheckable(False)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setContentsMargins(8, -1, 8, -1)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.phaseOffsetLabel_3 = QtGui.QLabel(self.groupBox_3)
        self.phaseOffsetLabel_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.phaseOffsetLabel_3.setAlignment(QtCore.Qt.AlignCenter)
        self.phaseOffsetLabel_3.setObjectName(_fromUtf8("phaseOffsetLabel_3"))
        self.gridLayout_3.addWidget(self.phaseOffsetLabel_3, 4, 1, 1, 1)
        self.NanglesLabel = QtGui.QLabel(self.groupBox_3)
        self.NanglesLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.NanglesLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.NanglesLabel.setObjectName(_fromUtf8("NanglesLabel"))
        self.gridLayout_3.addWidget(self.NanglesLabel, 5, 1, 1, 1)
        self.findModDepthsPushButton = QtGui.QPushButton(self.groupBox_3)
        self.findModDepthsPushButton.setMinimumSize(QtCore.QSize(101, 27))
        self.findModDepthsPushButton.setObjectName(_fromUtf8("findModDepthsPushButton"))
        self.gridLayout_3.addWidget(self.findModDepthsPushButton, 6, 1, 1, 3)
        self.clearAllSpotsPushButton_4 = QtGui.QPushButton(self.groupBox_3)
        self.clearAllSpotsPushButton_4.setMinimumSize(QtCore.QSize(101, 27))
        self.clearAllSpotsPushButton_4.setObjectName(_fromUtf8("clearAllSpotsPushButton_4"))
        self.gridLayout_3.addWidget(self.clearAllSpotsPushButton_4, 11, 3, 1, 1)
        self.checkSpotValidityPushButton = QtGui.QPushButton(self.groupBox_3)
        self.checkSpotValidityPushButton.setMinimumSize(QtCore.QSize(101, 27))
        self.checkSpotValidityPushButton.setObjectName(_fromUtf8("checkSpotValidityPushButton"))
        self.gridLayout_3.addWidget(self.checkSpotValidityPushButton, 4, 3, 1, 1)
        self.cosineFitPushButton = QtGui.QPushButton(self.groupBox_3)
        self.cosineFitPushButton.setMinimumSize(QtCore.QSize(101, 27))
        self.cosineFitPushButton.setObjectName(_fromUtf8("cosineFitPushButton"))
        self.gridLayout_3.addWidget(self.cosineFitPushButton, 5, 3, 1, 1)
        self.SNRSpinBox = QtGui.QSpinBox(self.groupBox_3)
        self.SNRSpinBox.setProperty("value", 10)
        self.SNRSpinBox.setObjectName(_fromUtf8("SNRSpinBox"))
        self.gridLayout_3.addWidget(self.SNRSpinBox, 4, 2, 1, 1)
        self.ETrulerPushButton = QtGui.QPushButton(self.groupBox_3)
        self.ETrulerPushButton.setMinimumSize(QtCore.QSize(101, 27))
        self.ETrulerPushButton.setObjectName(_fromUtf8("ETrulerPushButton"))
        self.gridLayout_3.addWidget(self.ETrulerPushButton, 11, 2, 1, 1)
        self.NanglesSpinBox = QtGui.QSpinBox(self.groupBox_3)
        self.NanglesSpinBox.setMinimum(2)
        self.NanglesSpinBox.setMaximum(1000)
        self.NanglesSpinBox.setProperty("value", 91)
        self.NanglesSpinBox.setObjectName(_fromUtf8("NanglesSpinBox"))
        self.gridLayout_3.addWidget(self.NanglesSpinBox, 5, 2, 1, 1)
        self.initAnalysisPushButton = QtGui.QPushButton(self.groupBox_3)
        self.initAnalysisPushButton.setMinimumSize(QtCore.QSize(101, 27))
        self.initAnalysisPushButton.setObjectName(_fromUtf8("initAnalysisPushButton"))
        self.gridLayout_3.addWidget(self.initAnalysisPushButton, 2, 1, 1, 3)
        self.saveContrastImagesPushButton = QtGui.QPushButton(self.groupBox_3)
        self.saveContrastImagesPushButton.setMinimumSize(QtCore.QSize(101, 27))
        self.saveContrastImagesPushButton.setObjectName(_fromUtf8("saveContrastImagesPushButton"))
        self.gridLayout_3.addWidget(self.saveContrastImagesPushButton, 11, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.showWhatComboBox = QtGui.QComboBox(self.centralwidget)
        self.showWhatComboBox.setGeometry(QtCore.QRect(1077, 220, 151, 27))
        self.showWhatComboBox.setObjectName(_fromUtf8("showWhatComboBox"))
        self.showWhatComboBox.addItem(_fromUtf8(""))
        self.showWhatComboBox.addItem(_fromUtf8(""))
        self.showWhatComboBox.addItem(_fromUtf8(""))
        self.showWhatComboBox.addItem(_fromUtf8(""))
        self.showStuffComboBox = QtGui.QComboBox(self.centralwidget)
        self.showStuffComboBox.setGeometry(QtCore.QRect(470, 220, 151, 27))
        self.showStuffComboBox.setObjectName(_fromUtf8("showStuffComboBox"))
        self.showStuffComboBox.addItem(_fromUtf8(""))
        self.showStuffComboBox.addItem(_fromUtf8(""))
        self.showStuffComboBox.addItem(_fromUtf8(""))
        self.showStuffComboBox.addItem(_fromUtf8(""))
        self.showStuffComboBox.addItem(_fromUtf8(""))
        self.showStuffComboBox.addItem(_fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1255, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.whichSetupComboBox.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Data import and basic parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.phaseOffsetLabel.setText(QtGui.QApplication.translate("MainWindow", "phase offset [deg]", None, QtGui.QApplication.UnicodeUTF8))
        self.phaseOffsetLineEdit.setText(QtGui.QApplication.translate("MainWindow", "2.0", None, QtGui.QApplication.UnicodeUTF8))
        self.isLambda2PlateLabel.setText(QtGui.QApplication.translate("MainWindow", "exitation is lambda/2 plate?", None, QtGui.QApplication.UnicodeUTF8))
        self.whichSetupComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "old setup", None, QtGui.QApplication.UnicodeUTF8))
        self.whichSetupComboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "new setup (continuous excitation rotation)", None, QtGui.QApplication.UnicodeUTF8))
        self.whichSetupComboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "new setup (full stepwise mode)", None, QtGui.QApplication.UnicodeUTF8))
        self.selectDataDirPushButton.setText(QtGui.QApplication.translate("MainWindow", "select data directoy", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Spot helper", None, QtGui.QApplication.UnicodeUTF8))
        self.phaseOffsetLabel_2.setText(QtGui.QApplication.translate("MainWindow", "spot scale [pixel]", None, QtGui.QApplication.UnicodeUTF8))
        self.createSpotArrayPushButton.setText(QtGui.QApplication.translate("MainWindow", "create spot array", None, QtGui.QApplication.UnicodeUTF8))
        self.clearAllSpotsPushButton.setText(QtGui.QApplication.translate("MainWindow", "clear all spots", None, QtGui.QApplication.UnicodeUTF8))
        self.setBGSpotPushButton.setText(QtGui.QApplication.translate("MainWindow", "set BG spot", None, QtGui.QApplication.UnicodeUTF8))
        self.addSignalSpotPushButton.setText(QtGui.QApplication.translate("MainWindow", "add signal spot", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Analysis tools", None, QtGui.QApplication.UnicodeUTF8))
        self.phaseOffsetLabel_3.setText(QtGui.QApplication.translate("MainWindow", "SNR limit", None, QtGui.QApplication.UnicodeUTF8))
        self.NanglesLabel.setText(QtGui.QApplication.translate("MainWindow", "N_angles", None, QtGui.QApplication.UnicodeUTF8))
        self.findModDepthsPushButton.setText(QtGui.QApplication.translate("MainWindow", "find mod depths and phases", None, QtGui.QApplication.UnicodeUTF8))
        self.clearAllSpotsPushButton_4.setText(QtGui.QApplication.translate("MainWindow", "ET model", None, QtGui.QApplication.UnicodeUTF8))
        self.checkSpotValidityPushButton.setText(QtGui.QApplication.translate("MainWindow", "check", None, QtGui.QApplication.UnicodeUTF8))
        self.cosineFitPushButton.setText(QtGui.QApplication.translate("MainWindow", "cosine fit", None, QtGui.QApplication.UnicodeUTF8))
        self.ETrulerPushButton.setText(QtGui.QApplication.translate("MainWindow", "ET ruler", None, QtGui.QApplication.UnicodeUTF8))
        self.initAnalysisPushButton.setText(QtGui.QApplication.translate("MainWindow", "collect+startstop+assign", None, QtGui.QApplication.UnicodeUTF8))
        self.saveContrastImagesPushButton.setText(QtGui.QApplication.translate("MainWindow", "save images", None, QtGui.QApplication.UnicodeUTF8))
        self.showWhatComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "intensity trace", None, QtGui.QApplication.UnicodeUTF8))
        self.showWhatComboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "portrait data", None, QtGui.QApplication.UnicodeUTF8))
        self.showWhatComboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "portrait fit", None, QtGui.QApplication.UnicodeUTF8))
        self.showWhatComboBox.setItemText(3, QtGui.QApplication.translate("MainWindow", "portrait residual", None, QtGui.QApplication.UnicodeUTF8))
        self.showStuffComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "spots", None, QtGui.QApplication.UnicodeUTF8))
        self.showStuffComboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "M_ex", None, QtGui.QApplication.UnicodeUTF8))
        self.showStuffComboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "M_em", None, QtGui.QApplication.UnicodeUTF8))
        self.showStuffComboBox.setItemText(3, QtGui.QApplication.translate("MainWindow", "phase_ex", None, QtGui.QApplication.UnicodeUTF8))
        self.showStuffComboBox.setItemText(4, QtGui.QApplication.translate("MainWindow", "phase_em", None, QtGui.QApplication.UnicodeUTF8))
        self.showStuffComboBox.setItemText(5, QtGui.QApplication.translate("MainWindow", "ET_ruler", None, QtGui.QApplication.UnicodeUTF8))

