# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sm_detector_layout.ui'
#
# Created: Mon Nov 18 23:45:00 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1126, 940)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.imageview = QtGui.QWidget(self.centralwidget)
        self.imageview.setGeometry(QtCore.QRect(10, 100, 741, 741))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.imageview.setFont(font)
        self.imageview.setFocusPolicy(QtCore.Qt.NoFocus)
        self.imageview.setObjectName(_fromUtf8("imageview"))
        self.loadFilePushButton = QtGui.QPushButton(self.centralwidget)
        self.loadFilePushButton.setGeometry(QtCore.QRect(10, 10, 98, 27))
        self.loadFilePushButton.setObjectName(_fromUtf8("loadFilePushButton"))
        self.SPEFileLabel = QtGui.QLabel(self.centralwidget)
        self.SPEFileLabel.setGeometry(QtCore.QRect(180, 27, 931, 20))
        self.SPEFileLabel.setText(_fromUtf8(""))
        self.SPEFileLabel.setObjectName(_fromUtf8("SPEFileLabel"))
        self.frameSlider = QtGui.QSlider(self.centralwidget)
        self.frameSlider.setGeometry(QtCore.QRect(10, 60, 741, 29))
        self.frameSlider.setOrientation(QtCore.Qt.Horizontal)
        self.frameSlider.setObjectName(_fromUtf8("frameSlider"))
        self.frameAverageToggleButton = QtGui.QPushButton(self.centralwidget)
        self.frameAverageToggleButton.setEnabled(False)
        self.frameAverageToggleButton.setGeometry(QtCore.QRect(980, 210, 121, 27))
        self.frameAverageToggleButton.setCheckable(True)
        self.frameAverageToggleButton.setObjectName(_fromUtf8("frameAverageToggleButton"))
        self.showWhatComboBox = QtGui.QComboBox(self.centralwidget)
        self.showWhatComboBox.setGeometry(QtCore.QRect(770, 210, 201, 27))
        self.showWhatComboBox.setObjectName(_fromUtf8("showWhatComboBox"))
        self.showWhatComboBox.addItem(_fromUtf8(""))
        self.showWhatComboBox.addItem(_fromUtf8(""))
        self.showWhatComboBox.addItem(_fromUtf8(""))
        self.highlightClusterPositionsCheckBox = QtGui.QCheckBox(self.centralwidget)
        self.highlightClusterPositionsCheckBox.setGeometry(QtCore.QRect(770, 240, 201, 27))
        self.highlightClusterPositionsCheckBox.setCheckable(True)
        self.highlightClusterPositionsCheckBox.setObjectName(_fromUtf8("highlightClusterPositionsCheckBox"))
        self.filterAndClusterAllFramesPushButton = QtGui.QPushButton(self.centralwidget)
        self.filterAndClusterAllFramesPushButton.setGeometry(QtCore.QRect(900, 880, 201, 27))
        self.filterAndClusterAllFramesPushButton.setObjectName(_fromUtf8("filterAndClusterAllFramesPushButton"))
        self.cropPushButton = QtGui.QPushButton(self.centralwidget)
        self.cropPushButton.setEnabled(False)
        self.cropPushButton.setGeometry(QtCore.QRect(930, 160, 81, 27))
        self.cropPushButton.setObjectName(_fromUtf8("cropPushButton"))
        self.resetPushButton = QtGui.QPushButton(self.centralwidget)
        self.resetPushButton.setGeometry(QtCore.QRect(1020, 160, 81, 27))
        self.resetPushButton.setCheckable(False)
        self.resetPushButton.setObjectName(_fromUtf8("resetPushButton"))
        self.loadDefaultPushButton = QtGui.QPushButton(self.centralwidget)
        self.loadDefaultPushButton.setGeometry(QtCore.QRect(110, 10, 61, 31))
        self.loadDefaultPushButton.setObjectName(_fromUtf8("loadDefaultPushButton"))
        self.toolbar = QtGui.QWidget(self.centralwidget)
        self.toolbar.setGeometry(QtCore.QRect(10, 840, 741, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.toolbar.setFont(font)
        self.toolbar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.toolbar.setObjectName(_fromUtf8("toolbar"))
        self.createLineAveragePushButton = QtGui.QPushButton(self.centralwidget)
        self.createLineAveragePushButton.setGeometry(QtCore.QRect(770, 160, 151, 27))
        self.createLineAveragePushButton.setObjectName(_fromUtf8("createLineAveragePushButton"))
        self.toolBox = QtGui.QToolBox(self.centralwidget)
        self.toolBox.setGeometry(QtCore.QRect(770, 290, 341, 481))
        self.toolBox.setFrameShape(QtGui.QFrame.StyledPanel)
        self.toolBox.setFrameShadow(QtGui.QFrame.Sunken)
        self.toolBox.setLineWidth(2)
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.page_pixel_correlator = QtGui.QWidget()
        self.page_pixel_correlator.setGeometry(QtCore.QRect(0, 0, 339, 386))
        self.page_pixel_correlator.setObjectName(_fromUtf8("page_pixel_correlator"))
        self.correlateNRowsSpinBox = QtGui.QSpinBox(self.page_pixel_correlator)
        self.correlateNRowsSpinBox.setGeometry(QtCore.QRect(190, 3, 60, 27))
        self.correlateNRowsSpinBox.setMinimum(1)
        self.correlateNRowsSpinBox.setProperty("value", 2)
        self.correlateNRowsSpinBox.setObjectName(_fromUtf8("correlateNRowsSpinBox"))
        self.correlateNColumnsSpinBox = QtGui.QSpinBox(self.page_pixel_correlator)
        self.correlateNColumnsSpinBox.setGeometry(QtCore.QRect(190, 35, 60, 27))
        self.correlateNColumnsSpinBox.setMinimum(1)
        self.correlateNColumnsSpinBox.setProperty("value", 2)
        self.correlateNColumnsSpinBox.setObjectName(_fromUtf8("correlateNColumnsSpinBox"))
        self.label_10 = QtGui.QLabel(self.page_pixel_correlator)
        self.label_10.setGeometry(QtCore.QRect(30, 10, 151, 17))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.page_pixel_correlator)
        self.label_11.setGeometry(QtCore.QRect(30, 40, 151, 17))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.useCorrelatorCheckBox = QtGui.QCheckBox(self.page_pixel_correlator)
        self.useCorrelatorCheckBox.setGeometry(QtCore.QRect(30, 140, 201, 27))
        self.useCorrelatorCheckBox.setCheckable(True)
        self.useCorrelatorCheckBox.setChecked(True)
        self.useCorrelatorCheckBox.setObjectName(_fromUtf8("useCorrelatorCheckBox"))
        self.applyCorrelatorPushButton = QtGui.QPushButton(self.page_pixel_correlator)
        self.applyCorrelatorPushButton.setGeometry(QtCore.QRect(60, 90, 271, 27))
        self.applyCorrelatorPushButton.setObjectName(_fromUtf8("applyCorrelatorPushButton"))
        self.toolBox.addItem(self.page_pixel_correlator, _fromUtf8(""))
        self.page_2d_fourier = QtGui.QWidget()
        self.page_2d_fourier.setGeometry(QtCore.QRect(0, 0, 339, 386))
        self.page_2d_fourier.setObjectName(_fromUtf8("page_2d_fourier"))
        self.filterOperationComboBox = QtGui.QComboBox(self.page_2d_fourier)
        self.filterOperationComboBox.setGeometry(QtCore.QRect(230, 70, 91, 27))
        self.filterOperationComboBox.setObjectName(_fromUtf8("filterOperationComboBox"))
        self.filterOperationComboBox.addItem(_fromUtf8(""))
        self.filterOperationComboBox.addItem(_fromUtf8(""))
        self.filterOperationComboBox.addItem(_fromUtf8(""))
        self.applyFilterPushButton = QtGui.QPushButton(self.page_2d_fourier)
        self.applyFilterPushButton.setGeometry(QtCore.QRect(220, 100, 101, 27))
        self.applyFilterPushButton.setObjectName(_fromUtf8("applyFilterPushButton"))
        self.lowFreqLineEdit = QtGui.QLineEdit(self.page_2d_fourier)
        self.lowFreqLineEdit.setGeometry(QtCore.QRect(240, 5, 51, 27))
        self.lowFreqLineEdit.setObjectName(_fromUtf8("lowFreqLineEdit"))
        self.label_3 = QtGui.QLabel(self.page_2d_fourier)
        self.label_3.setGeometry(QtCore.QRect(300, 10, 31, 20))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_2 = QtGui.QLabel(self.page_2d_fourier)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 221, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.highFreqLineEdit = QtGui.QLineEdit(self.page_2d_fourier)
        self.highFreqLineEdit.setGeometry(QtCore.QRect(240, 40, 51, 27))
        self.highFreqLineEdit.setObjectName(_fromUtf8("highFreqLineEdit"))
        self.label = QtGui.QLabel(self.page_2d_fourier)
        self.label.setGeometry(QtCore.QRect(20, 10, 221, 17))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_4 = QtGui.QLabel(self.page_2d_fourier)
        self.label_4.setGeometry(QtCore.QRect(300, 40, 31, 20))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.maskview = QtGui.QWidget(self.page_2d_fourier)
        self.maskview.setGeometry(QtCore.QRect(40, 130, 271, 251))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.maskview.setFont(font)
        self.maskview.setFocusPolicy(QtCore.Qt.NoFocus)
        self.maskview.setObjectName(_fromUtf8("maskview"))
        self.label_5 = QtGui.QLabel(self.page_2d_fourier)
        self.label_5.setGeometry(QtCore.QRect(110, 70, 121, 20))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_9 = QtGui.QLabel(self.page_2d_fourier)
        self.label_9.setGeometry(QtCore.QRect(23, 110, 91, 20))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.toolBox.addItem(self.page_2d_fourier, _fromUtf8(""))
        self.page_cluster_detection = QtGui.QWidget()
        self.page_cluster_detection.setGeometry(QtCore.QRect(0, 0, 339, 386))
        self.page_cluster_detection.setObjectName(_fromUtf8("page_cluster_detection"))
        self.label_8 = QtGui.QLabel(self.page_cluster_detection)
        self.label_8.setGeometry(QtCore.QRect(20, 230, 281, 30))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.clusterSizeThresholdLabel = QtGui.QLabel(self.page_cluster_detection)
        self.clusterSizeThresholdLabel.setGeometry(QtCore.QRect(260, 190, 71, 20))
        self.clusterSizeThresholdLabel.setObjectName(_fromUtf8("clusterSizeThresholdLabel"))
        self.clusterDistanceThresholdLabel = QtGui.QLabel(self.page_cluster_detection)
        self.clusterDistanceThresholdLabel.setGeometry(QtCore.QRect(260, 260, 71, 20))
        self.clusterDistanceThresholdLabel.setObjectName(_fromUtf8("clusterDistanceThresholdLabel"))
        self.clusterIntensityThresholdLabel = QtGui.QLabel(self.page_cluster_detection)
        self.clusterIntensityThresholdLabel.setGeometry(QtCore.QRect(260, 130, 61, 20))
        self.clusterIntensityThresholdLabel.setObjectName(_fromUtf8("clusterIntensityThresholdLabel"))
        self.label_6 = QtGui.QLabel(self.page_cluster_detection)
        self.label_6.setGeometry(QtCore.QRect(20, 110, 281, 20))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.clusterDistanceThresholdSlider = QtGui.QSlider(self.page_cluster_detection)
        self.clusterDistanceThresholdSlider.setGeometry(QtCore.QRect(20, 260, 221, 29))
        self.clusterDistanceThresholdSlider.setMaximum(50)
        self.clusterDistanceThresholdSlider.setPageStep(3)
        self.clusterDistanceThresholdSlider.setProperty("value", 4)
        self.clusterDistanceThresholdSlider.setOrientation(QtCore.Qt.Horizontal)
        self.clusterDistanceThresholdSlider.setObjectName(_fromUtf8("clusterDistanceThresholdSlider"))
        self.clusterSizeThresholdSlider = QtGui.QSlider(self.page_cluster_detection)
        self.clusterSizeThresholdSlider.setGeometry(QtCore.QRect(20, 190, 221, 29))
        self.clusterSizeThresholdSlider.setMaximum(20)
        self.clusterSizeThresholdSlider.setPageStep(3)
        self.clusterSizeThresholdSlider.setProperty("value", 4)
        self.clusterSizeThresholdSlider.setOrientation(QtCore.Qt.Horizontal)
        self.clusterSizeThresholdSlider.setObjectName(_fromUtf8("clusterSizeThresholdSlider"))
        self.label_7 = QtGui.QLabel(self.page_cluster_detection)
        self.label_7.setGeometry(QtCore.QRect(20, 170, 281, 20))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.clusterIntensityThresholdSlider = QtGui.QSlider(self.page_cluster_detection)
        self.clusterIntensityThresholdSlider.setGeometry(QtCore.QRect(20, 130, 221, 29))
        self.clusterIntensityThresholdSlider.setMaximum(15)
        self.clusterIntensityThresholdSlider.setPageStep(3)
        self.clusterIntensityThresholdSlider.setProperty("value", 3)
        self.clusterIntensityThresholdSlider.setOrientation(QtCore.Qt.Horizontal)
        self.clusterIntensityThresholdSlider.setObjectName(_fromUtf8("clusterIntensityThresholdSlider"))
        self.findClustersPushButton = QtGui.QPushButton(self.page_cluster_detection)
        self.findClustersPushButton.setGeometry(QtCore.QRect(140, 390, 181, 27))
        self.findClustersPushButton.setObjectName(_fromUtf8("findClustersPushButton"))
        self.clusterFrameThresholdSlider = QtGui.QSlider(self.page_cluster_detection)
        self.clusterFrameThresholdSlider.setGeometry(QtCore.QRect(20, 330, 221, 29))
        self.clusterFrameThresholdSlider.setMaximum(20)
        self.clusterFrameThresholdSlider.setPageStep(3)
        self.clusterFrameThresholdSlider.setProperty("value", 4)
        self.clusterFrameThresholdSlider.setOrientation(QtCore.Qt.Horizontal)
        self.clusterFrameThresholdSlider.setObjectName(_fromUtf8("clusterFrameThresholdSlider"))
        self.label_12 = QtGui.QLabel(self.page_cluster_detection)
        self.label_12.setGeometry(QtCore.QRect(20, 300, 281, 30))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.clusterFrameThresholdLabel = QtGui.QLabel(self.page_cluster_detection)
        self.clusterFrameThresholdLabel.setGeometry(QtCore.QRect(260, 330, 71, 20))
        self.clusterFrameThresholdLabel.setObjectName(_fromUtf8("clusterFrameThresholdLabel"))
        self.toolBox.addItem(self.page_cluster_detection, _fromUtf8(""))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(770, 30, 331, 101))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.addFitExclusionZonePushButton = QtGui.QPushButton(self.groupBox)
        self.addFitExclusionZonePushButton.setGeometry(QtCore.QRect(10, 20, 161, 27))
        self.addFitExclusionZonePushButton.setObjectName(_fromUtf8("addFitExclusionZonePushButton"))
        self.resetFitExclusionZonePushButton = QtGui.QPushButton(self.groupBox)
        self.resetFitExclusionZonePushButton.setGeometry(QtCore.QRect(180, 20, 141, 27))
        self.resetFitExclusionZonePushButton.setObjectName(_fromUtf8("resetFitExclusionZonePushButton"))
        self.blankFitPushButton = QtGui.QPushButton(self.groupBox)
        self.blankFitPushButton.setGeometry(QtCore.QRect(180, 60, 141, 30))
        self.blankFitPushButton.setObjectName(_fromUtf8("blankFitPushButton"))
        self.showBoolimageCheckBox = QtGui.QCheckBox(self.groupBox)
        self.showBoolimageCheckBox.setGeometry(QtCore.QRect(20, 60, 141, 27))
        self.showBoolimageCheckBox.setCheckable(True)
        self.showBoolimageCheckBox.setObjectName(_fromUtf8("showBoolimageCheckBox"))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(2)
        self.filterOperationComboBox.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.loadFilePushButton.setText(QtGui.QApplication.translate("MainWindow", "load SPE file", None, QtGui.QApplication.UnicodeUTF8))
        self.frameAverageToggleButton.setText(QtGui.QApplication.translate("MainWindow", "frame average", None, QtGui.QApplication.UnicodeUTF8))
        self.showWhatComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "original image", None, QtGui.QApplication.UnicodeUTF8))
        self.showWhatComboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "filtered image", None, QtGui.QApplication.UnicodeUTF8))
        self.showWhatComboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "clusters", None, QtGui.QApplication.UnicodeUTF8))
        self.highlightClusterPositionsCheckBox.setText(QtGui.QApplication.translate("MainWindow", "highlight cluster positions", None, QtGui.QApplication.UnicodeUTF8))
        self.filterAndClusterAllFramesPushButton.setText(QtGui.QApplication.translate("MainWindow", "sm detect all frames", None, QtGui.QApplication.UnicodeUTF8))
        self.cropPushButton.setText(QtGui.QApplication.translate("MainWindow", "crop", None, QtGui.QApplication.UnicodeUTF8))
        self.resetPushButton.setText(QtGui.QApplication.translate("MainWindow", "reset", None, QtGui.QApplication.UnicodeUTF8))
        self.loadDefaultPushButton.setText(QtGui.QApplication.translate("MainWindow", "*", None, QtGui.QApplication.UnicodeUTF8))
        self.createLineAveragePushButton.setText(QtGui.QApplication.translate("MainWindow", "create line average", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "correlate N rows:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "correlate N columns:", None, QtGui.QApplication.UnicodeUTF8))
        self.useCorrelatorCheckBox.setText(QtGui.QApplication.translate("MainWindow", "use correlator in analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.applyCorrelatorPushButton.setText(QtGui.QApplication.translate("MainWindow", "apply right now (undo requires reset)", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_pixel_correlator), QtGui.QApplication.translate("MainWindow", ">>  Pixel correlator", None, QtGui.QApplication.UnicodeUTF8))
        self.filterOperationComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "normal", None, QtGui.QApplication.UnicodeUTF8))
        self.filterOperationComboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "inverted", None, QtGui.QApplication.UnicodeUTF8))
        self.filterOperationComboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "gaussian", None, QtGui.QApplication.UnicodeUTF8))
        self.applyFilterPushButton.setText(QtGui.QApplication.translate("MainWindow", "apply filter", None, QtGui.QApplication.UnicodeUTF8))
        self.lowFreqLineEdit.setText(QtGui.QApplication.translate("MainWindow", "15", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "px", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "highest acceptable \'wavelength\':", None, QtGui.QApplication.UnicodeUTF8))
        self.highFreqLineEdit.setText(QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "lowest acceptable \'wavelength\':", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "px", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "operation mode:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "mask shape:", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2d_fourier), QtGui.QApplication.translate("MainWindow", ">>  2D Fourier filter", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "clusters must be this far apart:", None, QtGui.QApplication.UnicodeUTF8))
        self.clusterSizeThresholdLabel.setText(QtGui.QApplication.translate("MainWindow", "4 pixel", None, QtGui.QApplication.UnicodeUTF8))
        self.clusterDistanceThresholdLabel.setText(QtGui.QApplication.translate("MainWindow", "4 pixel", None, QtGui.QApplication.UnicodeUTF8))
        self.clusterIntensityThresholdLabel.setText(QtGui.QApplication.translate("MainWindow", "3 std", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "clustering intensity threshold:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "clustering size threshold:", None, QtGui.QApplication.UnicodeUTF8))
        self.findClustersPushButton.setText(QtGui.QApplication.translate("MainWindow", "find clusters in this frame", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "and must appear in at least:", None, QtGui.QApplication.UnicodeUTF8))
        self.clusterFrameThresholdLabel.setText(QtGui.QApplication.translate("MainWindow", "2 frames", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_cluster_detection), QtGui.QApplication.translate("MainWindow", "vv  Cluster detection", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "blank fit", None, QtGui.QApplication.UnicodeUTF8))
        self.addFitExclusionZonePushButton.setText(QtGui.QApplication.translate("MainWindow", "add fit exclusion zone", None, QtGui.QApplication.UnicodeUTF8))
        self.resetFitExclusionZonePushButton.setText(QtGui.QApplication.translate("MainWindow", "reset to full image", None, QtGui.QApplication.UnicodeUTF8))
        self.blankFitPushButton.setText(QtGui.QApplication.translate("MainWindow", "fit and subtract", None, QtGui.QApplication.UnicodeUTF8))
        self.showBoolimageCheckBox.setText(QtGui.QApplication.translate("MainWindow", "show boolimage", None, QtGui.QApplication.UnicodeUTF8))

