# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sm_detector_layout.ui'
#
# Created: Fri Nov 22 13:53:52 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from mymplcanvas import MyMplCanvas
from matplotlib.backends.backend_qt4agg import NavigationToolbar2QTAgg as NavigationToolbar

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1126, 940)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.imageview = MyMplCanvas(self.centralwidget, width=10, height=10, dpi=75)
        self.imageview.setGeometry(QtCore.QRect(10, 100, 741, 741))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.imageview.setFont(font)
        self.imageview.setFocusPolicy(QtCore.Qt.NoFocus)
        self.imageview.setObjectName(_fromUtf8("imageview"))
        self.logScaleComboBox = QtGui.QComboBox(self.imageview)
        self.logScaleComboBox.setGeometry(QtCore.QRect(640, 0, 101, 27))
        self.logScaleComboBox.setObjectName(_fromUtf8("logScaleComboBox"))
        self.logScaleComboBox.addItem(_fromUtf8(""))
        self.logScaleComboBox.addItem(_fromUtf8(""))
        self.cmapComboBox = QtGui.QComboBox(self.imageview)
        self.cmapComboBox.setGeometry(QtCore.QRect(530, 0, 101, 27))
        self.cmapComboBox.setObjectName(_fromUtf8("cmapComboBox"))
        self.cmapComboBox.addItem(_fromUtf8(""))
        self.cmapComboBox.addItem(_fromUtf8(""))
        self.cmapComboBox.addItem(_fromUtf8(""))
        self.cmapComboBox.addItem(_fromUtf8(""))
        self.loadFilePushButton = QtGui.QPushButton(self.centralwidget)
        self.loadFilePushButton.setGeometry(QtCore.QRect(10, 10, 98, 27))
        self.loadFilePushButton.setObjectName(_fromUtf8("loadFilePushButton"))
        self.SPEFileLabel = QtGui.QLabel(self.centralwidget)
        self.SPEFileLabel.setGeometry(QtCore.QRect(180, 16, 591, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.SPEFileLabel.setFont(font)
        self.SPEFileLabel.setText(_fromUtf8(""))
        self.SPEFileLabel.setWordWrap(True)
        self.SPEFileLabel.setObjectName(_fromUtf8("SPEFileLabel"))
        self.frameSlider = QtGui.QSlider(self.centralwidget)
        self.frameSlider.setGeometry(QtCore.QRect(10, 60, 741, 29))
        self.frameSlider.setOrientation(QtCore.Qt.Horizontal)
        self.frameSlider.setObjectName(_fromUtf8("frameSlider"))
        self.frameAverageToggleButton = QtGui.QPushButton(self.centralwidget)
        self.frameAverageToggleButton.setEnabled(False)
        self.frameAverageToggleButton.setGeometry(QtCore.QRect(980, 180, 121, 27))
        self.frameAverageToggleButton.setCheckable(True)
        self.frameAverageToggleButton.setObjectName(_fromUtf8("frameAverageToggleButton"))
        self.showWhatComboBox = QtGui.QComboBox(self.centralwidget)
        self.showWhatComboBox.setGeometry(QtCore.QRect(770, 180, 201, 27))
        self.showWhatComboBox.setObjectName(_fromUtf8("showWhatComboBox"))
        self.showWhatComboBox.addItem(_fromUtf8(""))
        self.showWhatComboBox.addItem(_fromUtf8(""))
        self.showWhatComboBox.addItem(_fromUtf8(""))
        self.highlightClusterPositionsCheckBox = QtGui.QCheckBox(self.centralwidget)
        self.highlightClusterPositionsCheckBox.setGeometry(QtCore.QRect(770, 240, 201, 27))
        self.highlightClusterPositionsCheckBox.setCheckable(True)
        self.highlightClusterPositionsCheckBox.setObjectName(_fromUtf8("highlightClusterPositionsCheckBox"))
        self.cropPushButton = QtGui.QPushButton(self.centralwidget)
        self.cropPushButton.setEnabled(False)
        self.cropPushButton.setGeometry(QtCore.QRect(930, 10, 81, 27))
        self.cropPushButton.setObjectName(_fromUtf8("cropPushButton"))
        self.resetPushButton = QtGui.QPushButton(self.centralwidget)
        self.resetPushButton.setGeometry(QtCore.QRect(1020, 10, 81, 27))
        self.resetPushButton.setCheckable(False)
        self.resetPushButton.setObjectName(_fromUtf8("resetPushButton"))
        self.loadDefaultPushButton = QtGui.QPushButton(self.centralwidget)
        self.loadDefaultPushButton.setGeometry(QtCore.QRect(110, 10, 61, 31))
        self.loadDefaultPushButton.setObjectName(_fromUtf8("loadDefaultPushButton"))
        self.toolbar = NavigationToolbar(self.imageview, self.centralwidget)
        self.toolbar.setGeometry(QtCore.QRect(10, 840, 741, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.toolbar.setFont(font)
        self.toolbar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.toolbar.setObjectName(_fromUtf8("toolbar"))
        self.createLineAveragePushButton = QtGui.QPushButton(self.centralwidget)
        self.createLineAveragePushButton.setGeometry(QtCore.QRect(770, 10, 151, 27))
        self.createLineAveragePushButton.setObjectName(_fromUtf8("createLineAveragePushButton"))
        self.toolBox = QtGui.QToolBox(self.centralwidget)
        self.toolBox.setGeometry(QtCore.QRect(770, 290, 341, 611))
        self.toolBox.setFrameShape(QtGui.QFrame.StyledPanel)
        self.toolBox.setFrameShadow(QtGui.QFrame.Sunken)
        self.toolBox.setLineWidth(2)
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.page_pixel_correlator = QtGui.QWidget()
        self.page_pixel_correlator.setGeometry(QtCore.QRect(0, 0, 339, 516))
        self.page_pixel_correlator.setObjectName(_fromUtf8("page_pixel_correlator"))
        self.useCorrelatorCheckBox = QtGui.QCheckBox(self.page_pixel_correlator)
        self.useCorrelatorCheckBox.setGeometry(QtCore.QRect(20, 10, 201, 27))
        self.useCorrelatorCheckBox.setCheckable(True)
        self.useCorrelatorCheckBox.setChecked(True)
        self.useCorrelatorCheckBox.setObjectName(_fromUtf8("useCorrelatorCheckBox"))
        self.applyCorrelatorPushButton = QtGui.QPushButton(self.page_pixel_correlator)
        self.applyCorrelatorPushButton.setGeometry(QtCore.QRect(20, 80, 271, 27))
        self.applyCorrelatorPushButton.setObjectName(_fromUtf8("applyCorrelatorPushButton"))
        self.fourthRootInCorrelatorCheckBox = QtGui.QCheckBox(self.page_pixel_correlator)
        self.fourthRootInCorrelatorCheckBox.setGeometry(QtCore.QRect(20, 40, 261, 27))
        self.fourthRootInCorrelatorCheckBox.setCheckable(True)
        self.fourthRootInCorrelatorCheckBox.setChecked(True)
        self.fourthRootInCorrelatorCheckBox.setObjectName(_fromUtf8("fourthRootInCorrelatorCheckBox"))
        self.toolBox.addItem(self.page_pixel_correlator, _fromUtf8(""))
        self.page_2d_fourier = QtGui.QWidget()
        self.page_2d_fourier.setGeometry(QtCore.QRect(0, 0, 339, 516))
        self.page_2d_fourier.setObjectName(_fromUtf8("page_2d_fourier"))
        self.filterOperationComboBox = QtGui.QComboBox(self.page_2d_fourier)
        self.filterOperationComboBox.setGeometry(QtCore.QRect(230, 70, 91, 27))
        self.filterOperationComboBox.setObjectName(_fromUtf8("filterOperationComboBox"))
        self.filterOperationComboBox.addItem(_fromUtf8(""))
        self.filterOperationComboBox.addItem(_fromUtf8(""))
        self.filterOperationComboBox.addItem(_fromUtf8(""))
        self.applyFilterPushButton = QtGui.QPushButton(self.page_2d_fourier)
        self.applyFilterPushButton.setGeometry(QtCore.QRect(220, 100, 101, 27))
        self.applyFilterPushButton.setObjectName(_fromUtf8("applyFilterPushButton"))
        self.lowFreqLineEdit = QtGui.QLineEdit(self.page_2d_fourier)
        self.lowFreqLineEdit.setGeometry(QtCore.QRect(240, 5, 51, 27))
        self.lowFreqLineEdit.setObjectName(_fromUtf8("lowFreqLineEdit"))
        self.label_3 = QtGui.QLabel(self.page_2d_fourier)
        self.label_3.setGeometry(QtCore.QRect(300, 10, 31, 20))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_2 = QtGui.QLabel(self.page_2d_fourier)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 221, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.highFreqLineEdit = QtGui.QLineEdit(self.page_2d_fourier)
        self.highFreqLineEdit.setGeometry(QtCore.QRect(240, 40, 51, 27))
        self.highFreqLineEdit.setObjectName(_fromUtf8("highFreqLineEdit"))
        self.label = QtGui.QLabel(self.page_2d_fourier)
        self.label.setGeometry(QtCore.QRect(20, 10, 221, 17))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_4 = QtGui.QLabel(self.page_2d_fourier)
        self.label_4.setGeometry(QtCore.QRect(300, 40, 31, 20))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.maskview = MyMplCanvas(self.page_2d_fourier, width=2, height=2, dpi=75)
        self.maskview.setGeometry(QtCore.QRect(40, 130, 271, 251))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.maskview.setFont(font)
        self.maskview.setFocusPolicy(QtCore.Qt.NoFocus)
        self.maskview.setObjectName(_fromUtf8("maskview"))
        self.label_5 = QtGui.QLabel(self.page_2d_fourier)
        self.label_5.setGeometry(QtCore.QRect(110, 70, 121, 20))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_9 = QtGui.QLabel(self.page_2d_fourier)
        self.label_9.setGeometry(QtCore.QRect(23, 110, 91, 20))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.toolBox.addItem(self.page_2d_fourier, _fromUtf8(""))
        self.page_cluster_detection = QtGui.QWidget()
        self.page_cluster_detection.setGeometry(QtCore.QRect(0, 0, 339, 516))
        self.page_cluster_detection.setObjectName(_fromUtf8("page_cluster_detection"))
        self.clusterIntensityThresholdLabel = QtGui.QLabel(self.page_cluster_detection)
        self.clusterIntensityThresholdLabel.setGeometry(QtCore.QRect(260, 60, 61, 20))
        self.clusterIntensityThresholdLabel.setObjectName(_fromUtf8("clusterIntensityThresholdLabel"))
        self.label_6 = QtGui.QLabel(self.page_cluster_detection)
        self.label_6.setGeometry(QtCore.QRect(20, 43, 281, 20))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.minClusterSizeThresholdSlider = QtGui.QSlider(self.page_cluster_detection)
        self.minClusterSizeThresholdSlider.setGeometry(QtCore.QRect(20, 185, 221, 29))
        self.minClusterSizeThresholdSlider.setMaximum(20)
        self.minClusterSizeThresholdSlider.setPageStep(1)
        self.minClusterSizeThresholdSlider.setProperty("value", 4)
        self.minClusterSizeThresholdSlider.setOrientation(QtCore.Qt.Horizontal)
        self.minClusterSizeThresholdSlider.setObjectName(_fromUtf8("minClusterSizeThresholdSlider"))
        self.label_7 = QtGui.QLabel(self.page_cluster_detection)
        self.label_7.setGeometry(QtCore.QRect(20, 170, 281, 20))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.clusterIntensityThresholdSlider = QtGui.QSlider(self.page_cluster_detection)
        self.clusterIntensityThresholdSlider.setGeometry(QtCore.QRect(20, 60, 221, 29))
        self.clusterIntensityThresholdSlider.setMaximum(150)
        self.clusterIntensityThresholdSlider.setPageStep(10)
        self.clusterIntensityThresholdSlider.setProperty("value", 30)
        self.clusterIntensityThresholdSlider.setOrientation(QtCore.Qt.Horizontal)
        self.clusterIntensityThresholdSlider.setObjectName(_fromUtf8("clusterIntensityThresholdSlider"))
        self.findClustersPushButton = QtGui.QPushButton(self.page_cluster_detection)
        self.findClustersPushButton.setGeometry(QtCore.QRect(20, 135, 151, 27))
        self.findClustersPushButton.setCheckable(False)
        self.findClustersPushButton.setObjectName(_fromUtf8("findClustersPushButton"))
        self.useOriginalDataToggleButton = QtGui.QPushButton(self.page_cluster_detection)
        self.useOriginalDataToggleButton.setGeometry(QtCore.QRect(20, 10, 151, 27))
        self.useOriginalDataToggleButton.setCheckable(True)
        self.useOriginalDataToggleButton.setChecked(True)
        self.useOriginalDataToggleButton.setObjectName(_fromUtf8("useOriginalDataToggleButton"))
        self.useFourierdDataToggleButton = QtGui.QPushButton(self.page_cluster_detection)
        self.useFourierdDataToggleButton.setGeometry(QtCore.QRect(170, 10, 151, 27))
        self.useFourierdDataToggleButton.setCheckable(True)
        self.useFourierdDataToggleButton.setObjectName(_fromUtf8("useFourierdDataToggleButton"))
        self.groupBox_2 = QtGui.QGroupBox(self.page_cluster_detection)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 350, 301, 121))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.clusterCrossFrameDistanceThresholdSlider = QtGui.QSlider(self.groupBox_2)
        self.clusterCrossFrameDistanceThresholdSlider.setEnabled(False)
        self.clusterCrossFrameDistanceThresholdSlider.setGeometry(QtCore.QRect(20, 88, 201, 29))
        self.clusterCrossFrameDistanceThresholdSlider.setMinimum(1)
        self.clusterCrossFrameDistanceThresholdSlider.setMaximum(20)
        self.clusterCrossFrameDistanceThresholdSlider.setPageStep(1)
        self.clusterCrossFrameDistanceThresholdSlider.setProperty("value", 4)
        self.clusterCrossFrameDistanceThresholdSlider.setOrientation(QtCore.Qt.Horizontal)
        self.clusterCrossFrameDistanceThresholdSlider.setObjectName(_fromUtf8("clusterCrossFrameDistanceThresholdSlider"))
        self.clusterMergeAcrossFramesCheckBox = QtGui.QCheckBox(self.groupBox_2)
        self.clusterMergeAcrossFramesCheckBox.setEnabled(False)
        self.clusterMergeAcrossFramesCheckBox.setGeometry(QtCore.QRect(20, 70, 231, 22))
        self.clusterMergeAcrossFramesCheckBox.setChecked(False)
        self.clusterMergeAcrossFramesCheckBox.setObjectName(_fromUtf8("clusterMergeAcrossFramesCheckBox"))
        self.clusterDistanceThresholdSlider = QtGui.QSlider(self.groupBox_2)
        self.clusterDistanceThresholdSlider.setEnabled(False)
        self.clusterDistanceThresholdSlider.setGeometry(QtCore.QRect(20, 40, 201, 29))
        self.clusterDistanceThresholdSlider.setMinimum(1)
        self.clusterDistanceThresholdSlider.setMaximum(20)
        self.clusterDistanceThresholdSlider.setPageStep(1)
        self.clusterDistanceThresholdSlider.setProperty("value", 4)
        self.clusterDistanceThresholdSlider.setOrientation(QtCore.Qt.Horizontal)
        self.clusterDistanceThresholdSlider.setObjectName(_fromUtf8("clusterDistanceThresholdSlider"))
        self.clusterWithinFrameMinDistanceCheckBox = QtGui.QCheckBox(self.groupBox_2)
        self.clusterWithinFrameMinDistanceCheckBox.setGeometry(QtCore.QRect(20, 22, 261, 22))
        self.clusterWithinFrameMinDistanceCheckBox.setObjectName(_fromUtf8("clusterWithinFrameMinDistanceCheckBox"))
        self.clusterDistanceWithinFrameThresholdLabel = QtGui.QLabel(self.groupBox_2)
        self.clusterDistanceWithinFrameThresholdLabel.setGeometry(QtCore.QRect(230, 43, 71, 20))
        self.clusterDistanceWithinFrameThresholdLabel.setObjectName(_fromUtf8("clusterDistanceWithinFrameThresholdLabel"))
        self.clusterDistanceAcrossFramesThresholdLabel = QtGui.QLabel(self.groupBox_2)
        self.clusterDistanceAcrossFramesThresholdLabel.setGeometry(QtCore.QRect(230, 90, 61, 20))
        self.clusterDistanceAcrossFramesThresholdLabel.setObjectName(_fromUtf8("clusterDistanceAcrossFramesThresholdLabel"))
        self.minClusterSizeThresholdLabel = QtGui.QLabel(self.page_cluster_detection)
        self.minClusterSizeThresholdLabel.setGeometry(QtCore.QRect(260, 185, 61, 20))
        self.minClusterSizeThresholdLabel.setObjectName(_fromUtf8("minClusterSizeThresholdLabel"))
        self.writeCoordsPushButton = QtGui.QPushButton(self.page_cluster_detection)
        self.writeCoordsPushButton.setGeometry(QtCore.QRect(130, 480, 201, 27))
        self.writeCoordsPushButton.setCheckable(False)
        self.writeCoordsPushButton.setObjectName(_fromUtf8("writeCoordsPushButton"))
        self.maxClusterSizeThresholdSlider = QtGui.QSlider(self.page_cluster_detection)
        self.maxClusterSizeThresholdSlider.setGeometry(QtCore.QRect(20, 230, 221, 29))
        self.maxClusterSizeThresholdSlider.setMinimum(1)
        self.maxClusterSizeThresholdSlider.setMaximum(100)
        self.maxClusterSizeThresholdSlider.setPageStep(1)
        self.maxClusterSizeThresholdSlider.setProperty("value", 20)
        self.maxClusterSizeThresholdSlider.setOrientation(QtCore.Qt.Horizontal)
        self.maxClusterSizeThresholdSlider.setObjectName(_fromUtf8("maxClusterSizeThresholdSlider"))
        self.maxClusterSizeThresholdLabel = QtGui.QLabel(self.page_cluster_detection)
        self.maxClusterSizeThresholdLabel.setGeometry(QtCore.QRect(260, 231, 61, 20))
        self.maxClusterSizeThresholdLabel.setObjectName(_fromUtf8("maxClusterSizeThresholdLabel"))
        self.label_8 = QtGui.QLabel(self.page_cluster_detection)
        self.label_8.setGeometry(QtCore.QRect(20, 216, 281, 20))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.findClustersNewPushButton = QtGui.QPushButton(self.page_cluster_detection)
        self.findClustersNewPushButton.setGeometry(QtCore.QRect(180, 135, 121, 27))
        self.findClustersNewPushButton.setCheckable(False)
        self.findClustersNewPushButton.setObjectName(_fromUtf8("findClustersNewPushButton"))
        self.clusterBGIntensityThresholdSlider = QtGui.QSlider(self.page_cluster_detection)
        self.clusterBGIntensityThresholdSlider.setGeometry(QtCore.QRect(20, 104, 221, 29))
        self.clusterBGIntensityThresholdSlider.setMaximum(150)
        self.clusterBGIntensityThresholdSlider.setPageStep(10)
        self.clusterBGIntensityThresholdSlider.setProperty("value", 30)
        self.clusterBGIntensityThresholdSlider.setOrientation(QtCore.Qt.Horizontal)
        self.clusterBGIntensityThresholdSlider.setObjectName(_fromUtf8("clusterBGIntensityThresholdSlider"))
        self.clusterBGIntensityThresholdLabel = QtGui.QLabel(self.page_cluster_detection)
        self.clusterBGIntensityThresholdLabel.setGeometry(QtCore.QRect(260, 100, 61, 20))
        self.clusterBGIntensityThresholdLabel.setObjectName(_fromUtf8("clusterBGIntensityThresholdLabel"))
        self.clustersMustAppearInAtLeastNFramesCheckBox = QtGui.QCheckBox(self.page_cluster_detection)
        self.clustersMustAppearInAtLeastNFramesCheckBox.setEnabled(True)
        self.clustersMustAppearInAtLeastNFramesCheckBox.setGeometry(QtCore.QRect(20, 260, 261, 22))
        self.clustersMustAppearInAtLeastNFramesCheckBox.setChecked(True)
        self.clustersMustAppearInAtLeastNFramesCheckBox.setObjectName(_fromUtf8("clustersMustAppearInAtLeastNFramesCheckBox"))
        self.clusterFrameThresholdSlider = QtGui.QSlider(self.page_cluster_detection)
        self.clusterFrameThresholdSlider.setGeometry(QtCore.QRect(20, 280, 221, 29))
        self.clusterFrameThresholdSlider.setMinimum(1)
        self.clusterFrameThresholdSlider.setMaximum(24)
        self.clusterFrameThresholdSlider.setPageStep(1)
        self.clusterFrameThresholdSlider.setProperty("value", 4)
        self.clusterFrameThresholdSlider.setOrientation(QtCore.Qt.Horizontal)
        self.clusterFrameThresholdSlider.setObjectName(_fromUtf8("clusterFrameThresholdSlider"))
        self.clusterFrameThresholdLabel = QtGui.QLabel(self.page_cluster_detection)
        self.clusterFrameThresholdLabel.setGeometry(QtCore.QRect(260, 280, 61, 20))
        self.clusterFrameThresholdLabel.setObjectName(_fromUtf8("clusterFrameThresholdLabel"))
        self.clusterBGIntensityCheckBox = QtGui.QCheckBox(self.page_cluster_detection)
        self.clusterBGIntensityCheckBox.setGeometry(QtCore.QRect(20, 90, 261, 22))
        self.clusterBGIntensityCheckBox.setObjectName(_fromUtf8("clusterBGIntensityCheckBox"))
        self.toolBox.addItem(self.page_cluster_detection, _fromUtf8(""))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(770, 60, 331, 101))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.addFitExclusionZonePushButton = QtGui.QPushButton(self.groupBox)
        self.addFitExclusionZonePushButton.setGeometry(QtCore.QRect(10, 20, 161, 27))
        self.addFitExclusionZonePushButton.setObjectName(_fromUtf8("addFitExclusionZonePushButton"))
        self.resetFitExclusionZonePushButton = QtGui.QPushButton(self.groupBox)
        self.resetFitExclusionZonePushButton.setGeometry(QtCore.QRect(180, 20, 141, 27))
        self.resetFitExclusionZonePushButton.setObjectName(_fromUtf8("resetFitExclusionZonePushButton"))
        self.blankFitPushButton = QtGui.QPushButton(self.groupBox)
        self.blankFitPushButton.setGeometry(QtCore.QRect(180, 60, 141, 30))
        self.blankFitPushButton.setObjectName(_fromUtf8("blankFitPushButton"))
        self.showBoolimageCheckBox = QtGui.QCheckBox(self.groupBox)
        self.showBoolimageCheckBox.setGeometry(QtCore.QRect(20, 60, 141, 27))
        self.showBoolimageCheckBox.setCheckable(True)
        self.showBoolimageCheckBox.setObjectName(_fromUtf8("showBoolimageCheckBox"))
        self.histogramToggleButton = QtGui.QPushButton(self.centralwidget)
        self.histogramToggleButton.setGeometry(QtCore.QRect(770, 210, 201, 27))
        self.histogramToggleButton.setCheckable(True)
        self.histogramToggleButton.setObjectName(_fromUtf8("histogramToggleButton"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        self.filterOperationComboBox.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.logScaleComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "normal scale", None, QtGui.QApplication.UnicodeUTF8))
        self.logScaleComboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "log scale", None, QtGui.QApplication.UnicodeUTF8))
        self.cmapComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "gray", None, QtGui.QApplication.UnicodeUTF8))
        self.cmapComboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "jet", None, QtGui.QApplication.UnicodeUTF8))
        self.cmapComboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "hsv", None, QtGui.QApplication.UnicodeUTF8))
        self.cmapComboBox.setItemText(3, QtGui.QApplication.translate("MainWindow", "heat", None, QtGui.QApplication.UnicodeUTF8))
        self.loadFilePushButton.setText(QtGui.QApplication.translate("MainWindow", "load SPE file", None, QtGui.QApplication.UnicodeUTF8))
        self.frameAverageToggleButton.setText(QtGui.QApplication.translate("MainWindow", "frame average", None, QtGui.QApplication.UnicodeUTF8))
        self.showWhatComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "original image", None, QtGui.QApplication.UnicodeUTF8))
        self.showWhatComboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "filtered image", None, QtGui.QApplication.UnicodeUTF8))
        self.showWhatComboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "clusters", None, QtGui.QApplication.UnicodeUTF8))
        self.highlightClusterPositionsCheckBox.setText(QtGui.QApplication.translate("MainWindow", "highlight cluster positions", None, QtGui.QApplication.UnicodeUTF8))
        self.cropPushButton.setText(QtGui.QApplication.translate("MainWindow", "crop", None, QtGui.QApplication.UnicodeUTF8))
        self.resetPushButton.setText(QtGui.QApplication.translate("MainWindow", "reset", None, QtGui.QApplication.UnicodeUTF8))
        self.loadDefaultPushButton.setText(QtGui.QApplication.translate("MainWindow", "*", None, QtGui.QApplication.UnicodeUTF8))
        self.createLineAveragePushButton.setText(QtGui.QApplication.translate("MainWindow", "create line average", None, QtGui.QApplication.UnicodeUTF8))
        self.useCorrelatorCheckBox.setText(QtGui.QApplication.translate("MainWindow", "use correlator in analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.applyCorrelatorPushButton.setText(QtGui.QApplication.translate("MainWindow", "apply right now (undo requires reset)", None, QtGui.QApplication.UnicodeUTF8))
        self.fourthRootInCorrelatorCheckBox.setText(QtGui.QApplication.translate("MainWindow", "apply fourth root after correlation", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_pixel_correlator), QtGui.QApplication.translate("MainWindow", ">>  Pixel correlator", None, QtGui.QApplication.UnicodeUTF8))
        self.filterOperationComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "normal", None, QtGui.QApplication.UnicodeUTF8))
        self.filterOperationComboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "inverted", None, QtGui.QApplication.UnicodeUTF8))
        self.filterOperationComboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "gaussian", None, QtGui.QApplication.UnicodeUTF8))
        self.applyFilterPushButton.setText(QtGui.QApplication.translate("MainWindow", "apply filter", None, QtGui.QApplication.UnicodeUTF8))
        self.lowFreqLineEdit.setText(QtGui.QApplication.translate("MainWindow", "15", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "px", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "highest acceptable \'wavelength\':", None, QtGui.QApplication.UnicodeUTF8))
        self.highFreqLineEdit.setText(QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "lowest acceptable \'wavelength\':", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "px", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "operation mode:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "mask shape:", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2d_fourier), QtGui.QApplication.translate("MainWindow", ">>  2D Fourier filter", None, QtGui.QApplication.UnicodeUTF8))
        self.clusterIntensityThresholdLabel.setText(QtGui.QApplication.translate("MainWindow", "3 std", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "clustering intensity threshold:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "cluster min size threshold:", None, QtGui.QApplication.UnicodeUTF8))
        self.findClustersPushButton.setText(QtGui.QApplication.translate("MainWindow", "find clusters", None, QtGui.QApplication.UnicodeUTF8))
        self.useOriginalDataToggleButton.setText(QtGui.QApplication.translate("MainWindow", "use original data", None, QtGui.QApplication.UnicodeUTF8))
        self.useFourierdDataToggleButton.setText(QtGui.QApplication.translate("MainWindow", "use Fourier\'d data", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Cluster validation:", None, QtGui.QApplication.UnicodeUTF8))
        self.clusterMergeAcrossFramesCheckBox.setText(QtGui.QApplication.translate("MainWindow", "across-frames merging distance:", None, QtGui.QApplication.UnicodeUTF8))
        self.clusterWithinFrameMinDistanceCheckBox.setText(QtGui.QApplication.translate("MainWindow", "clusters must be this far apart in a frame:", None, QtGui.QApplication.UnicodeUTF8))
        self.clusterDistanceWithinFrameThresholdLabel.setText(QtGui.QApplication.translate("MainWindow", "4 pixel", None, QtGui.QApplication.UnicodeUTF8))
        self.clusterDistanceAcrossFramesThresholdLabel.setText(QtGui.QApplication.translate("MainWindow", "4 pixel", None, QtGui.QApplication.UnicodeUTF8))
        self.minClusterSizeThresholdLabel.setText(QtGui.QApplication.translate("MainWindow", "2 pixel", None, QtGui.QApplication.UnicodeUTF8))
        self.writeCoordsPushButton.setText(QtGui.QApplication.translate("MainWindow", "write coords to file", None, QtGui.QApplication.UnicodeUTF8))
        self.maxClusterSizeThresholdLabel.setText(QtGui.QApplication.translate("MainWindow", "20 pixel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "cluster max size threshold:", None, QtGui.QApplication.UnicodeUTF8))
        self.findClustersNewPushButton.setText(QtGui.QApplication.translate("MainWindow", "--> new version", None, QtGui.QApplication.UnicodeUTF8))
        self.clusterBGIntensityThresholdLabel.setText(QtGui.QApplication.translate("MainWindow", "3 std", None, QtGui.QApplication.UnicodeUTF8))
        self.clustersMustAppearInAtLeastNFramesCheckBox.setText(QtGui.QApplication.translate("MainWindow", "clusters must appear in at least:", None, QtGui.QApplication.UnicodeUTF8))
        self.clusterFrameThresholdLabel.setText(QtGui.QApplication.translate("MainWindow", "2 frames", None, QtGui.QApplication.UnicodeUTF8))
        self.clusterBGIntensityCheckBox.setText(QtGui.QApplication.translate("MainWindow", "BG intensity threshold:", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_cluster_detection), QtGui.QApplication.translate("MainWindow", "vv  Cluster detection", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "blank fit", None, QtGui.QApplication.UnicodeUTF8))
        self.addFitExclusionZonePushButton.setText(QtGui.QApplication.translate("MainWindow", "add fit exclusion zone", None, QtGui.QApplication.UnicodeUTF8))
        self.resetFitExclusionZonePushButton.setText(QtGui.QApplication.translate("MainWindow", "reset to full image", None, QtGui.QApplication.UnicodeUTF8))
        self.blankFitPushButton.setText(QtGui.QApplication.translate("MainWindow", "fit and subtract", None, QtGui.QApplication.UnicodeUTF8))
        self.showBoolimageCheckBox.setText(QtGui.QApplication.translate("MainWindow", "show boolimage", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramToggleButton.setText(QtGui.QApplication.translate("MainWindow", "histogram", None, QtGui.QApplication.UnicodeUTF8))

