# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sm_detector_layout.ui'
#
# Created: Sun May  4 12:39:41 2014
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1126, 810)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.imageview = QtGui.QWidget(self.centralwidget)
        self.imageview.setGeometry(QtCore.QRect(60, 90, 641, 641))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.imageview.setFont(font)
        self.imageview.setFocusPolicy(QtCore.Qt.NoFocus)
        self.imageview.setObjectName(_fromUtf8("imageview"))
        self.logScaleComboBox = QtGui.QComboBox(self.imageview)
        self.logScaleComboBox.setGeometry(QtCore.QRect(540, 0, 101, 27))
        self.logScaleComboBox.setObjectName(_fromUtf8("logScaleComboBox"))
        self.logScaleComboBox.addItem(_fromUtf8(""))
        self.logScaleComboBox.addItem(_fromUtf8(""))
        self.cmapComboBox = QtGui.QComboBox(self.imageview)
        self.cmapComboBox.setGeometry(QtCore.QRect(430, 0, 101, 27))
        self.cmapComboBox.setObjectName(_fromUtf8("cmapComboBox"))
        self.cmapComboBox.addItem(_fromUtf8(""))
        self.cmapComboBox.addItem(_fromUtf8(""))
        self.cmapComboBox.addItem(_fromUtf8(""))
        self.cmapComboBox.addItem(_fromUtf8(""))
        self.specialForOldDataPushButton = QtGui.QPushButton(self.imageview)
        self.specialForOldDataPushButton.setEnabled(False)
        self.specialForOldDataPushButton.setGeometry(QtCore.QRect(0, 0, 121, 21))
        self.specialForOldDataPushButton.setObjectName(_fromUtf8("specialForOldDataPushButton"))
        self.specialForOldDataExPushButton = QtGui.QPushButton(self.imageview)
        self.specialForOldDataExPushButton.setEnabled(False)
        self.specialForOldDataExPushButton.setGeometry(QtCore.QRect(130, 0, 41, 21))
        self.specialForOldDataExPushButton.setObjectName(_fromUtf8("specialForOldDataExPushButton"))
        self.specialForOldDataEmPushButton = QtGui.QPushButton(self.imageview)
        self.specialForOldDataEmPushButton.setEnabled(False)
        self.specialForOldDataEmPushButton.setGeometry(QtCore.QRect(170, 0, 41, 21))
        self.specialForOldDataEmPushButton.setObjectName(_fromUtf8("specialForOldDataEmPushButton"))
        self.specialForOldDataMapPushButton = QtGui.QPushButton(self.imageview)
        self.specialForOldDataMapPushButton.setEnabled(False)
        self.specialForOldDataMapPushButton.setGeometry(QtCore.QRect(230, 0, 41, 21))
        self.specialForOldDataMapPushButton.setObjectName(_fromUtf8("specialForOldDataMapPushButton"))
        self.specialForOldDataAllPushButton = QtGui.QPushButton(self.imageview)
        self.specialForOldDataAllPushButton.setEnabled(False)
        self.specialForOldDataAllPushButton.setGeometry(QtCore.QRect(290, 0, 41, 21))
        self.specialForOldDataAllPushButton.setObjectName(_fromUtf8("specialForOldDataAllPushButton"))
        self.loadFilePushButton = QtGui.QPushButton(self.centralwidget)
        self.loadFilePushButton.setGeometry(QtCore.QRect(10, 10, 98, 27))
        self.loadFilePushButton.setObjectName(_fromUtf8("loadFilePushButton"))
        self.SPEFileLabel = QtGui.QLabel(self.centralwidget)
        self.SPEFileLabel.setGeometry(QtCore.QRect(180, 16, 591, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.SPEFileLabel.setFont(font)
        self.SPEFileLabel.setText(_fromUtf8(""))
        self.SPEFileLabel.setWordWrap(True)
        self.SPEFileLabel.setObjectName(_fromUtf8("SPEFileLabel"))
        self.frameSlider = QtGui.QSlider(self.centralwidget)
        self.frameSlider.setGeometry(QtCore.QRect(10, 50, 741, 29))
        self.frameSlider.setOrientation(QtCore.Qt.Horizontal)
        self.frameSlider.setObjectName(_fromUtf8("frameSlider"))
        self.frameAverageToggleButton = QtGui.QPushButton(self.centralwidget)
        self.frameAverageToggleButton.setEnabled(False)
        self.frameAverageToggleButton.setGeometry(QtCore.QRect(980, 240, 121, 27))
        self.frameAverageToggleButton.setCheckable(True)
        self.frameAverageToggleButton.setObjectName(_fromUtf8("frameAverageToggleButton"))
        self.showWhatComboBox = QtGui.QComboBox(self.centralwidget)
        self.showWhatComboBox.setGeometry(QtCore.QRect(770, 240, 201, 27))
        self.showWhatComboBox.setObjectName(_fromUtf8("showWhatComboBox"))
        self.showWhatComboBox.addItem(_fromUtf8(""))
        self.showWhatComboBox.addItem(_fromUtf8(""))
        self.showWhatComboBox.addItem(_fromUtf8(""))
        self.highlightClusterPositionsCheckBox = QtGui.QCheckBox(self.centralwidget)
        self.highlightClusterPositionsCheckBox.setGeometry(QtCore.QRect(770, 300, 201, 27))
        self.highlightClusterPositionsCheckBox.setCheckable(True)
        self.highlightClusterPositionsCheckBox.setObjectName(_fromUtf8("highlightClusterPositionsCheckBox"))
        self.resetPushButton = QtGui.QPushButton(self.centralwidget)
        self.resetPushButton.setGeometry(QtCore.QRect(1040, 10, 81, 27))
        self.resetPushButton.setCheckable(False)
        self.resetPushButton.setObjectName(_fromUtf8("resetPushButton"))
        self.loadDefaultPushButton = QtGui.QPushButton(self.centralwidget)
        self.loadDefaultPushButton.setGeometry(QtCore.QRect(110, 10, 61, 31))
        self.loadDefaultPushButton.setObjectName(_fromUtf8("loadDefaultPushButton"))
        self.toolbar = QtGui.QWidget(self.centralwidget)
        self.toolbar.setGeometry(QtCore.QRect(60, 730, 641, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.toolbar.setFont(font)
        self.toolbar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.toolbar.setObjectName(_fromUtf8("toolbar"))
        self.createLineAveragePushButton = QtGui.QPushButton(self.centralwidget)
        self.createLineAveragePushButton.setGeometry(QtCore.QRect(770, 10, 101, 27))
        self.createLineAveragePushButton.setObjectName(_fromUtf8("createLineAveragePushButton"))
        self.toolBox = QtGui.QToolBox(self.centralwidget)
        self.toolBox.setGeometry(QtCore.QRect(770, 340, 341, 431))
        self.toolBox.setFrameShape(QtGui.QFrame.StyledPanel)
        self.toolBox.setFrameShadow(QtGui.QFrame.Sunken)
        self.toolBox.setLineWidth(2)
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.page_pixel_correlator = QtGui.QWidget()
        self.page_pixel_correlator.setGeometry(QtCore.QRect(0, 0, 339, 336))
        self.page_pixel_correlator.setObjectName(_fromUtf8("page_pixel_correlator"))
        self.useCorrelatorCheckBox = QtGui.QCheckBox(self.page_pixel_correlator)
        self.useCorrelatorCheckBox.setGeometry(QtCore.QRect(20, 10, 201, 27))
        self.useCorrelatorCheckBox.setCheckable(True)
        self.useCorrelatorCheckBox.setChecked(True)
        self.useCorrelatorCheckBox.setObjectName(_fromUtf8("useCorrelatorCheckBox"))
        self.applyCorrelatorPushButton = QtGui.QPushButton(self.page_pixel_correlator)
        self.applyCorrelatorPushButton.setGeometry(QtCore.QRect(20, 80, 271, 27))
        self.applyCorrelatorPushButton.setObjectName(_fromUtf8("applyCorrelatorPushButton"))
        self.fourthRootInCorrelatorCheckBox = QtGui.QCheckBox(self.page_pixel_correlator)
        self.fourthRootInCorrelatorCheckBox.setGeometry(QtCore.QRect(20, 40, 261, 27))
        self.fourthRootInCorrelatorCheckBox.setCheckable(True)
        self.fourthRootInCorrelatorCheckBox.setChecked(True)
        self.fourthRootInCorrelatorCheckBox.setObjectName(_fromUtf8("fourthRootInCorrelatorCheckBox"))
        self.toolBox.addItem(self.page_pixel_correlator, _fromUtf8(""))
        self.page_2d_fourier = QtGui.QWidget()
        self.page_2d_fourier.setGeometry(QtCore.QRect(0, 0, 339, 336))
        self.page_2d_fourier.setObjectName(_fromUtf8("page_2d_fourier"))
        self.filterOperationComboBox = QtGui.QComboBox(self.page_2d_fourier)
        self.filterOperationComboBox.setGeometry(QtCore.QRect(230, 70, 91, 27))
        self.filterOperationComboBox.setObjectName(_fromUtf8("filterOperationComboBox"))
        self.filterOperationComboBox.addItem(_fromUtf8(""))
        self.filterOperationComboBox.addItem(_fromUtf8(""))
        self.filterOperationComboBox.addItem(_fromUtf8(""))
        self.applyFilterPushButton = QtGui.QPushButton(self.page_2d_fourier)
        self.applyFilterPushButton.setGeometry(QtCore.QRect(220, 100, 101, 27))
        self.applyFilterPushButton.setObjectName(_fromUtf8("applyFilterPushButton"))
        self.lowFreqLineEdit = QtGui.QLineEdit(self.page_2d_fourier)
        self.lowFreqLineEdit.setGeometry(QtCore.QRect(240, 5, 51, 27))
        self.lowFreqLineEdit.setObjectName(_fromUtf8("lowFreqLineEdit"))
        self.label_3 = QtGui.QLabel(self.page_2d_fourier)
        self.label_3.setGeometry(QtCore.QRect(300, 10, 31, 20))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_2 = QtGui.QLabel(self.page_2d_fourier)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 221, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.highFreqLineEdit = QtGui.QLineEdit(self.page_2d_fourier)
        self.highFreqLineEdit.setGeometry(QtCore.QRect(240, 40, 51, 27))
        self.highFreqLineEdit.setObjectName(_fromUtf8("highFreqLineEdit"))
        self.label = QtGui.QLabel(self.page_2d_fourier)
        self.label.setGeometry(QtCore.QRect(20, 10, 221, 17))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_4 = QtGui.QLabel(self.page_2d_fourier)
        self.label_4.setGeometry(QtCore.QRect(300, 40, 31, 20))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.maskview = QtGui.QWidget(self.page_2d_fourier)
        self.maskview.setGeometry(QtCore.QRect(40, 130, 271, 251))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.maskview.setFont(font)
        self.maskview.setFocusPolicy(QtCore.Qt.NoFocus)
        self.maskview.setObjectName(_fromUtf8("maskview"))
        self.label_5 = QtGui.QLabel(self.page_2d_fourier)
        self.label_5.setGeometry(QtCore.QRect(110, 70, 121, 20))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_9 = QtGui.QLabel(self.page_2d_fourier)
        self.label_9.setGeometry(QtCore.QRect(23, 110, 91, 20))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.toolBox.addItem(self.page_2d_fourier, _fromUtf8(""))
        self.page_cluster_detection = QtGui.QWidget()
        self.page_cluster_detection.setGeometry(QtCore.QRect(0, 0, 339, 336))
        self.page_cluster_detection.setObjectName(_fromUtf8("page_cluster_detection"))
        self.clusterIntensityThresholdLabel = QtGui.QLabel(self.page_cluster_detection)
        self.clusterIntensityThresholdLabel.setGeometry(QtCore.QRect(260, 60, 61, 20))
        self.clusterIntensityThresholdLabel.setObjectName(_fromUtf8("clusterIntensityThresholdLabel"))
        self.label_6 = QtGui.QLabel(self.page_cluster_detection)
        self.label_6.setGeometry(QtCore.QRect(20, 43, 281, 20))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.minClusterSizeThresholdSlider = QtGui.QSlider(self.page_cluster_detection)
        self.minClusterSizeThresholdSlider.setGeometry(QtCore.QRect(20, 105, 221, 29))
        self.minClusterSizeThresholdSlider.setMaximum(20)
        self.minClusterSizeThresholdSlider.setPageStep(1)
        self.minClusterSizeThresholdSlider.setProperty("value", 4)
        self.minClusterSizeThresholdSlider.setOrientation(QtCore.Qt.Horizontal)
        self.minClusterSizeThresholdSlider.setObjectName(_fromUtf8("minClusterSizeThresholdSlider"))
        self.label_7 = QtGui.QLabel(self.page_cluster_detection)
        self.label_7.setGeometry(QtCore.QRect(20, 90, 281, 20))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.clusterIntensityThresholdSlider = QtGui.QSlider(self.page_cluster_detection)
        self.clusterIntensityThresholdSlider.setGeometry(QtCore.QRect(20, 60, 221, 29))
        self.clusterIntensityThresholdSlider.setMaximum(150)
        self.clusterIntensityThresholdSlider.setPageStep(10)
        self.clusterIntensityThresholdSlider.setProperty("value", 30)
        self.clusterIntensityThresholdSlider.setTracking(True)
        self.clusterIntensityThresholdSlider.setOrientation(QtCore.Qt.Horizontal)
        self.clusterIntensityThresholdSlider.setObjectName(_fromUtf8("clusterIntensityThresholdSlider"))
        self.useOriginalDataToggleButton = QtGui.QPushButton(self.page_cluster_detection)
        self.useOriginalDataToggleButton.setGeometry(QtCore.QRect(20, 10, 151, 27))
        self.useOriginalDataToggleButton.setCheckable(True)
        self.useOriginalDataToggleButton.setChecked(True)
        self.useOriginalDataToggleButton.setObjectName(_fromUtf8("useOriginalDataToggleButton"))
        self.useFourierdDataToggleButton = QtGui.QPushButton(self.page_cluster_detection)
        self.useFourierdDataToggleButton.setGeometry(QtCore.QRect(170, 10, 151, 27))
        self.useFourierdDataToggleButton.setCheckable(True)
        self.useFourierdDataToggleButton.setObjectName(_fromUtf8("useFourierdDataToggleButton"))
        self.minClusterSizeThresholdLabel = QtGui.QLabel(self.page_cluster_detection)
        self.minClusterSizeThresholdLabel.setGeometry(QtCore.QRect(260, 105, 61, 20))
        self.minClusterSizeThresholdLabel.setObjectName(_fromUtf8("minClusterSizeThresholdLabel"))
        self.writeCoordsPushButton = QtGui.QPushButton(self.page_cluster_detection)
        self.writeCoordsPushButton.setGeometry(QtCore.QRect(170, 300, 151, 27))
        self.writeCoordsPushButton.setCheckable(False)
        self.writeCoordsPushButton.setObjectName(_fromUtf8("writeCoordsPushButton"))
        self.maxClusterSizeThresholdSlider = QtGui.QSlider(self.page_cluster_detection)
        self.maxClusterSizeThresholdSlider.setGeometry(QtCore.QRect(20, 150, 221, 29))
        self.maxClusterSizeThresholdSlider.setMinimum(1)
        self.maxClusterSizeThresholdSlider.setMaximum(100)
        self.maxClusterSizeThresholdSlider.setPageStep(1)
        self.maxClusterSizeThresholdSlider.setProperty("value", 40)
        self.maxClusterSizeThresholdSlider.setOrientation(QtCore.Qt.Horizontal)
        self.maxClusterSizeThresholdSlider.setObjectName(_fromUtf8("maxClusterSizeThresholdSlider"))
        self.maxClusterSizeThresholdLabel = QtGui.QLabel(self.page_cluster_detection)
        self.maxClusterSizeThresholdLabel.setGeometry(QtCore.QRect(260, 151, 61, 20))
        self.maxClusterSizeThresholdLabel.setObjectName(_fromUtf8("maxClusterSizeThresholdLabel"))
        self.label_8 = QtGui.QLabel(self.page_cluster_detection)
        self.label_8.setGeometry(QtCore.QRect(20, 136, 281, 20))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.findClustersNewPushButton = QtGui.QPushButton(self.page_cluster_detection)
        self.findClustersNewPushButton.setGeometry(QtCore.QRect(20, 300, 121, 27))
        self.findClustersNewPushButton.setCheckable(False)
        self.findClustersNewPushButton.setObjectName(_fromUtf8("findClustersNewPushButton"))
        self.clusterFrameThresholdSlider = QtGui.QSlider(self.page_cluster_detection)
        self.clusterFrameThresholdSlider.setGeometry(QtCore.QRect(20, 200, 221, 29))
        self.clusterFrameThresholdSlider.setMinimum(1)
        self.clusterFrameThresholdSlider.setMaximum(24)
        self.clusterFrameThresholdSlider.setPageStep(1)
        self.clusterFrameThresholdSlider.setProperty("value", 4)
        self.clusterFrameThresholdSlider.setOrientation(QtCore.Qt.Horizontal)
        self.clusterFrameThresholdSlider.setObjectName(_fromUtf8("clusterFrameThresholdSlider"))
        self.clusterFrameThresholdLabel = QtGui.QLabel(self.page_cluster_detection)
        self.clusterFrameThresholdLabel.setGeometry(QtCore.QRect(260, 200, 61, 20))
        self.clusterFrameThresholdLabel.setObjectName(_fromUtf8("clusterFrameThresholdLabel"))
        self.clusterDistanceThresholdSlider = QtGui.QSlider(self.page_cluster_detection)
        self.clusterDistanceThresholdSlider.setEnabled(True)
        self.clusterDistanceThresholdSlider.setGeometry(QtCore.QRect(20, 250, 201, 29))
        self.clusterDistanceThresholdSlider.setMinimum(1)
        self.clusterDistanceThresholdSlider.setMaximum(40)
        self.clusterDistanceThresholdSlider.setPageStep(1)
        self.clusterDistanceThresholdSlider.setProperty("value", 10)
        self.clusterDistanceThresholdSlider.setOrientation(QtCore.Qt.Horizontal)
        self.clusterDistanceThresholdSlider.setObjectName(_fromUtf8("clusterDistanceThresholdSlider"))
        self.clusterDistanceThresholdLabel = QtGui.QLabel(self.page_cluster_detection)
        self.clusterDistanceThresholdLabel.setGeometry(QtCore.QRect(260, 254, 71, 20))
        self.clusterDistanceThresholdLabel.setObjectName(_fromUtf8("clusterDistanceThresholdLabel"))
        self.label_10 = QtGui.QLabel(self.page_cluster_detection)
        self.label_10.setGeometry(QtCore.QRect(20, 234, 281, 17))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.page_cluster_detection)
        self.label_11.setGeometry(QtCore.QRect(20, 185, 281, 17))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.toolBox.addItem(self.page_cluster_detection, _fromUtf8(""))
        self.blankFitGroupBox = QtGui.QGroupBox(self.centralwidget)
        self.blankFitGroupBox.setEnabled(True)
        self.blankFitGroupBox.setGeometry(QtCore.QRect(770, 70, 331, 81))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.blankFitGroupBox.setFont(font)
        self.blankFitGroupBox.setObjectName(_fromUtf8("blankFitGroupBox"))
        self.addFitExclusionZonePushButton = QtGui.QPushButton(self.blankFitGroupBox)
        self.addFitExclusionZonePushButton.setGeometry(QtCore.QRect(10, 20, 161, 27))
        self.addFitExclusionZonePushButton.setObjectName(_fromUtf8("addFitExclusionZonePushButton"))
        self.resetFitExclusionZonePushButton = QtGui.QPushButton(self.blankFitGroupBox)
        self.resetFitExclusionZonePushButton.setGeometry(QtCore.QRect(180, 20, 141, 27))
        self.resetFitExclusionZonePushButton.setObjectName(_fromUtf8("resetFitExclusionZonePushButton"))
        self.blankFitPushButton = QtGui.QPushButton(self.blankFitGroupBox)
        self.blankFitPushButton.setGeometry(QtCore.QRect(180, 50, 141, 30))
        self.blankFitPushButton.setObjectName(_fromUtf8("blankFitPushButton"))
        self.showBoolimageCheckBox = QtGui.QCheckBox(self.blankFitGroupBox)
        self.showBoolimageCheckBox.setGeometry(QtCore.QRect(20, 50, 141, 27))
        self.showBoolimageCheckBox.setCheckable(True)
        self.showBoolimageCheckBox.setObjectName(_fromUtf8("showBoolimageCheckBox"))
        self.histogramToggleButton = QtGui.QPushButton(self.centralwidget)
        self.histogramToggleButton.setGeometry(QtCore.QRect(770, 270, 201, 27))
        self.histogramToggleButton.setCheckable(True)
        self.histogramToggleButton.setObjectName(_fromUtf8("histogramToggleButton"))
        self.bgCorrectPushButton = QtGui.QPushButton(self.centralwidget)
        self.bgCorrectPushButton.setEnabled(True)
        self.bgCorrectPushButton.setGeometry(QtCore.QRect(880, 10, 81, 27))
        self.bgCorrectPushButton.setObjectName(_fromUtf8("bgCorrectPushButton"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(770, 159, 331, 61))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.selectRectanglePushButton = QtGui.QPushButton(self.groupBox)
        self.selectRectanglePushButton.setGeometry(QtCore.QRect(30, 20, 141, 30))
        self.selectRectanglePushButton.setCheckable(True)
        self.selectRectanglePushButton.setObjectName(_fromUtf8("selectRectanglePushButton"))
        self.selectCirclePushButton = QtGui.QPushButton(self.groupBox)
        self.selectCirclePushButton.setGeometry(QtCore.QRect(180, 20, 141, 30))
        self.selectCirclePushButton.setCheckable(True)
        self.selectCirclePushButton.setObjectName(_fromUtf8("selectCirclePushButton"))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.cmapComboBox.setCurrentIndex(1)
        self.toolBox.setCurrentIndex(0)
        self.filterOperationComboBox.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.logScaleComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "normal scale", None, QtGui.QApplication.UnicodeUTF8))
        self.logScaleComboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "log scale", None, QtGui.QApplication.UnicodeUTF8))
        self.cmapComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "gray", None, QtGui.QApplication.UnicodeUTF8))
        self.cmapComboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "jet", None, QtGui.QApplication.UnicodeUTF8))
        self.cmapComboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "hsv", None, QtGui.QApplication.UnicodeUTF8))
        self.cmapComboBox.setItemText(3, QtGui.QApplication.translate("MainWindow", "heat", None, QtGui.QApplication.UnicodeUTF8))
        self.specialForOldDataPushButton.setText(QtGui.QApplication.translate("MainWindow", "special for old data ", None, QtGui.QApplication.UnicodeUTF8))
        self.specialForOldDataExPushButton.setText(QtGui.QApplication.translate("MainWindow", "ex", None, QtGui.QApplication.UnicodeUTF8))
        self.specialForOldDataEmPushButton.setText(QtGui.QApplication.translate("MainWindow", "em", None, QtGui.QApplication.UnicodeUTF8))
        self.specialForOldDataMapPushButton.setText(QtGui.QApplication.translate("MainWindow", "map", None, QtGui.QApplication.UnicodeUTF8))
        self.specialForOldDataAllPushButton.setText(QtGui.QApplication.translate("MainWindow", "all", None, QtGui.QApplication.UnicodeUTF8))
        self.loadFilePushButton.setText(QtGui.QApplication.translate("MainWindow", "load SPE file", None, QtGui.QApplication.UnicodeUTF8))
        self.frameAverageToggleButton.setText(QtGui.QApplication.translate("MainWindow", "frame average", None, QtGui.QApplication.UnicodeUTF8))
        self.showWhatComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "original image", None, QtGui.QApplication.UnicodeUTF8))
        self.showWhatComboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "filtered image", None, QtGui.QApplication.UnicodeUTF8))
        self.showWhatComboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "clusters", None, QtGui.QApplication.UnicodeUTF8))
        self.highlightClusterPositionsCheckBox.setText(QtGui.QApplication.translate("MainWindow", "highlight cluster positions", None, QtGui.QApplication.UnicodeUTF8))
        self.resetPushButton.setText(QtGui.QApplication.translate("MainWindow", "reset", None, QtGui.QApplication.UnicodeUTF8))
        self.loadDefaultPushButton.setText(QtGui.QApplication.translate("MainWindow", "*", None, QtGui.QApplication.UnicodeUTF8))
        self.createLineAveragePushButton.setText(QtGui.QApplication.translate("MainWindow", "line average", None, QtGui.QApplication.UnicodeUTF8))
        self.useCorrelatorCheckBox.setText(QtGui.QApplication.translate("MainWindow", "use correlator in analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.applyCorrelatorPushButton.setText(QtGui.QApplication.translate("MainWindow", "apply right now (undo requires reset)", None, QtGui.QApplication.UnicodeUTF8))
        self.fourthRootInCorrelatorCheckBox.setText(QtGui.QApplication.translate("MainWindow", "apply fourth root after correlation", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_pixel_correlator), QtGui.QApplication.translate("MainWindow", ">>  Pixel correlator", None, QtGui.QApplication.UnicodeUTF8))
        self.filterOperationComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "normal", None, QtGui.QApplication.UnicodeUTF8))
        self.filterOperationComboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "inverted", None, QtGui.QApplication.UnicodeUTF8))
        self.filterOperationComboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "gaussian", None, QtGui.QApplication.UnicodeUTF8))
        self.applyFilterPushButton.setText(QtGui.QApplication.translate("MainWindow", "apply filter", None, QtGui.QApplication.UnicodeUTF8))
        self.lowFreqLineEdit.setText(QtGui.QApplication.translate("MainWindow", "15", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "px", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "highest acceptable \'wavelength\':", None, QtGui.QApplication.UnicodeUTF8))
        self.highFreqLineEdit.setText(QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "lowest acceptable \'wavelength\':", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "px", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "operation mode:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "mask shape:", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2d_fourier), QtGui.QApplication.translate("MainWindow", ">>  2D Fourier filter", None, QtGui.QApplication.UnicodeUTF8))
        self.clusterIntensityThresholdLabel.setText(QtGui.QApplication.translate("MainWindow", "3 std", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "clustering intensity threshold:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "cluster min size threshold:", None, QtGui.QApplication.UnicodeUTF8))
        self.useOriginalDataToggleButton.setText(QtGui.QApplication.translate("MainWindow", "use original data", None, QtGui.QApplication.UnicodeUTF8))
        self.useFourierdDataToggleButton.setText(QtGui.QApplication.translate("MainWindow", "use Fourier\'d data", None, QtGui.QApplication.UnicodeUTF8))
        self.minClusterSizeThresholdLabel.setText(QtGui.QApplication.translate("MainWindow", "2 pixel", None, QtGui.QApplication.UnicodeUTF8))
        self.writeCoordsPushButton.setText(QtGui.QApplication.translate("MainWindow", "write coords to file", None, QtGui.QApplication.UnicodeUTF8))
        self.maxClusterSizeThresholdLabel.setText(QtGui.QApplication.translate("MainWindow", "40 pixel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "cluster max size threshold:", None, QtGui.QApplication.UnicodeUTF8))
        self.findClustersNewPushButton.setText(QtGui.QApplication.translate("MainWindow", "findClusters", None, QtGui.QApplication.UnicodeUTF8))
        self.clusterFrameThresholdLabel.setText(QtGui.QApplication.translate("MainWindow", "4 frames", None, QtGui.QApplication.UnicodeUTF8))
        self.clusterDistanceThresholdLabel.setText(QtGui.QApplication.translate("MainWindow", "10 pixel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "clusters must be this far apart in a frame:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "clusters must appear in at least:", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_cluster_detection), QtGui.QApplication.translate("MainWindow", "vv  Cluster detection", None, QtGui.QApplication.UnicodeUTF8))
        self.blankFitGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "blank fit", None, QtGui.QApplication.UnicodeUTF8))
        self.addFitExclusionZonePushButton.setText(QtGui.QApplication.translate("MainWindow", "add fit exclusion zone", None, QtGui.QApplication.UnicodeUTF8))
        self.resetFitExclusionZonePushButton.setText(QtGui.QApplication.translate("MainWindow", "reset to full image", None, QtGui.QApplication.UnicodeUTF8))
        self.blankFitPushButton.setText(QtGui.QApplication.translate("MainWindow", "fit and subtract", None, QtGui.QApplication.UnicodeUTF8))
        self.showBoolimageCheckBox.setText(QtGui.QApplication.translate("MainWindow", "show boolimage", None, QtGui.QApplication.UnicodeUTF8))
        self.histogramToggleButton.setText(QtGui.QApplication.translate("MainWindow", "histogram", None, QtGui.QApplication.UnicodeUTF8))
        self.bgCorrectPushButton.setText(QtGui.QApplication.translate("MainWindow", "bg correct", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Detection area", None, QtGui.QApplication.UnicodeUTF8))
        self.selectRectanglePushButton.setText(QtGui.QApplication.translate("MainWindow", "select rectangle", None, QtGui.QApplication.UnicodeUTF8))
        self.selectCirclePushButton.setText(QtGui.QApplication.translate("MainWindow", "select circle", None, QtGui.QApplication.UnicodeUTF8))

