# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'converter_gui_layout.ui'
#
# Created: Fri Aug 23 09:03:10 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(832, 661)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 90, 801, 131))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.pickEmMotorFilePushButton = QtGui.QPushButton(self.groupBox)
        self.pickEmMotorFilePushButton.setEnabled(True)
        self.pickEmMotorFilePushButton.setGeometry(QtCore.QRect(10, 60, 201, 27))
        self.pickEmMotorFilePushButton.setObjectName(_fromUtf8("pickEmMotorFilePushButton"))
        self.pickExMotorFilePushButton = QtGui.QPushButton(self.groupBox)
        self.pickExMotorFilePushButton.setGeometry(QtCore.QRect(10, 30, 201, 27))
        self.pickExMotorFilePushButton.setObjectName(_fromUtf8("pickExMotorFilePushButton"))
        self.pickSPEFilePushButton = QtGui.QPushButton(self.groupBox)
        self.pickSPEFilePushButton.setGeometry(QtCore.QRect(10, 90, 201, 27))
        self.pickSPEFilePushButton.setObjectName(_fromUtf8("pickSPEFilePushButton"))
        self.label_17 = QtGui.QLabel(self.groupBox)
        self.label_17.setGeometry(QtCore.QRect(220, 30, 561, 27))
        self.label_17.setText(_fromUtf8(""))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.emMotorFileLabel = QtGui.QLabel(self.groupBox)
        self.emMotorFileLabel.setGeometry(QtCore.QRect(220, 60, 351, 27))
        self.emMotorFileLabel.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.emMotorFileLabel.setText(_fromUtf8(""))
        self.emMotorFileLabel.setObjectName(_fromUtf8("emMotorFileLabel"))
        self.SPEFileLabel = QtGui.QLabel(self.groupBox)
        self.SPEFileLabel.setGeometry(QtCore.QRect(220, 90, 351, 27))
        self.SPEFileLabel.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.SPEFileLabel.setText(_fromUtf8(""))
        self.SPEFileLabel.setObjectName(_fromUtf8("SPEFileLabel"))
        self.exMotorFileLabel = QtGui.QLabel(self.groupBox)
        self.exMotorFileLabel.setGeometry(QtCore.QRect(220, 30, 351, 27))
        self.exMotorFileLabel.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.exMotorFileLabel.setText(_fromUtf8(""))
        self.exMotorFileLabel.setObjectName(_fromUtf8("exMotorFileLabel"))
        self.rotDirLabel = QtGui.QLabel(self.groupBox)
        self.rotDirLabel.setGeometry(QtCore.QRect(590, 30, 131, 27))
        self.rotDirLabel.setMinimumSize(QtCore.QSize(131, 0))
        self.rotDirLabel.setObjectName(_fromUtf8("rotDirLabel"))
        self.rotationDirectionComboBox = QtGui.QComboBox(self.groupBox)
        self.rotationDirectionComboBox.setGeometry(QtCore.QRect(720, 30, 61, 27))
        self.rotationDirectionComboBox.setObjectName(_fromUtf8("rotationDirectionComboBox"))
        self.rotationDirectionComboBox.addItem(_fromUtf8(""))
        self.rotationDirectionComboBox.addItem(_fromUtf8(""))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 220, 801, 341))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.formLayoutWidget = QtGui.QWidget(self.groupBox_2)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 30, 371, 301))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setMargin(0)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_2 = QtGui.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtGui.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.fullExPowerLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.fullExPowerLineEdit.setObjectName(_fromUtf8("fullExPowerLineEdit"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.fullExPowerLineEdit)
        self.wavelengthLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.wavelengthLineEdit.setObjectName(_fromUtf8("wavelengthLineEdit"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.wavelengthLineEdit)
        self.label_4 = QtGui.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.ODofFilterLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.ODofFilterLineEdit.setObjectName(_fromUtf8("ODofFilterLineEdit"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.ODofFilterLineEdit)
        self.label_5 = QtGui.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_5)
        self.exPowerAfterFilterLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.exPowerAfterFilterLineEdit.setObjectName(_fromUtf8("exPowerAfterFilterLineEdit"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.exPowerAfterFilterLineEdit)
        self.label_6 = QtGui.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_6)
        self.whichObjectiveComboBox = QtGui.QComboBox(self.formLayoutWidget)
        self.whichObjectiveComboBox.setObjectName(_fromUtf8("whichObjectiveComboBox"))
        self.whichObjectiveComboBox.addItem(_fromUtf8(""))
        self.whichObjectiveComboBox.addItem(_fromUtf8(""))
        self.whichObjectiveComboBox.addItem(_fromUtf8(""))
        self.whichObjectiveComboBox.addItem(_fromUtf8(""))
        self.whichObjectiveComboBox.addItem(_fromUtf8(""))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.whichObjectiveComboBox)
        self.label_7 = QtGui.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_7)
        self.NALineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.NALineEdit.setObjectName(_fromUtf8("NALineEdit"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.NALineEdit)
        self.label_8 = QtGui.QLabel(self.formLayoutWidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_8)
        self.whichCameraComboBox = QtGui.QComboBox(self.formLayoutWidget)
        self.whichCameraComboBox.setObjectName(_fromUtf8("whichCameraComboBox"))
        self.whichCameraComboBox.addItem(_fromUtf8(""))
        self.whichCameraComboBox.addItem(_fromUtf8(""))
        self.whichCameraComboBox.addItem(_fromUtf8(""))
        self.whichCameraComboBox.addItem(_fromUtf8(""))
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.whichCameraComboBox)
        self.label_9 = QtGui.QLabel(self.formLayoutWidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_9)
        self.realGainLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.realGainLineEdit.setObjectName(_fromUtf8("realGainLineEdit"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.realGainLineEdit)
        self.label_15 = QtGui.QLabel(self.formLayoutWidget)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_15)
        self.opticalElementInExcitationComboBox = QtGui.QComboBox(self.formLayoutWidget)
        self.opticalElementInExcitationComboBox.setObjectName(_fromUtf8("opticalElementInExcitationComboBox"))
        self.opticalElementInExcitationComboBox.addItem(_fromUtf8(""))
        self.opticalElementInExcitationComboBox.addItem(_fromUtf8(""))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.opticalElementInExcitationComboBox)
        self.formLayoutWidget_2 = QtGui.QWidget(self.groupBox_2)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(410, 30, 371, 61))
        self.formLayoutWidget_2.setObjectName(_fromUtf8("formLayoutWidget_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setMargin(0)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_10 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_10)
        self.label_11 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_11)
        self.phaseOffsetLineEdit = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.phaseOffsetLineEdit.setObjectName(_fromUtf8("phaseOffsetLineEdit"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.phaseOffsetLineEdit)
        self.formLayoutWidget_3 = QtGui.QWidget(self.groupBox_2)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(410, 100, 371, 91))
        self.formLayoutWidget_3.setObjectName(_fromUtf8("formLayoutWidget_3"))
        self.formLayout_3 = QtGui.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setMargin(0)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_12 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_12)
        self.label_13 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_13)
        self.modulationDepthLineEdit = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.modulationDepthLineEdit.setObjectName(_fromUtf8("modulationDepthLineEdit"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.modulationDepthLineEdit)
        self.phaseLineEdit = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.phaseLineEdit.setObjectName(_fromUtf8("phaseLineEdit"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.phaseLineEdit)
        self.label_14 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_14)
        self.plainTextEdit = QtGui.QPlainTextEdit(self.groupBox_2)
        self.plainTextEdit.setGeometry(QtCore.QRect(410, 220, 371, 101))
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.label_16 = QtGui.QLabel(self.groupBox_2)
        self.label_16.setGeometry(QtCore.QRect(410, 200, 200, 20))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 560, 801, 61))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.convertPushButton = QtGui.QPushButton(self.groupBox_3)
        self.convertPushButton.setGeometry(QtCore.QRect(10, 30, 201, 27))
        self.convertPushButton.setObjectName(_fromUtf8("convertPushButton"))
        self.OutputFileLabel = QtGui.QLabel(self.groupBox_3)
        self.OutputFileLabel.setGeometry(QtCore.QRect(220, 30, 341, 27))
        self.OutputFileLabel.setText(_fromUtf8(""))
        self.OutputFileLabel.setObjectName(_fromUtf8("OutputFileLabel"))
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 10, 801, 71))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.whichSetupComboBox = QtGui.QComboBox(self.groupBox_4)
        self.whichSetupComboBox.setGeometry(QtCore.QRect(10, 30, 621, 27))
        self.whichSetupComboBox.setObjectName(_fromUtf8("whichSetupComboBox"))
        self.whichSetupComboBox.addItem(_fromUtf8(""))
        self.whichSetupComboBox.addItem(_fromUtf8(""))
        self.whichSetupComboBox.addItem(_fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Input file(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.pickEmMotorFilePushButton.setText(QtGui.QApplication.translate("MainWindow", "Pick emission motor file", None, QtGui.QApplication.UnicodeUTF8))
        self.pickExMotorFilePushButton.setText(QtGui.QApplication.translate("MainWindow", "Pick excitation motor file", None, QtGui.QApplication.UnicodeUTF8))
        self.pickSPEFilePushButton.setText(QtGui.QApplication.translate("MainWindow", "SPE file name (for time axis)", None, QtGui.QApplication.UnicodeUTF8))
        self.rotDirLabel.setText(QtGui.QApplication.translate("MainWindow", "rotation direction:", None, QtGui.QApplication.UnicodeUTF8))
        self.rotationDirectionComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "CW", None, QtGui.QApplication.UnicodeUTF8))
        self.rotationDirectionComboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "CCW", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Header info", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Wavelength [nm]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "FullExPower [mW]", None, QtGui.QApplication.UnicodeUTF8))
        self.fullExPowerLineEdit.setText(QtGui.QApplication.translate("MainWindow", "NaN", None, QtGui.QApplication.UnicodeUTF8))
        self.wavelengthLineEdit.setText(QtGui.QApplication.translate("MainWindow", "NaN", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "OD of filter", None, QtGui.QApplication.UnicodeUTF8))
        self.ODofFilterLineEdit.setText(QtGui.QApplication.translate("MainWindow", "NaN", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "ExPower after filter [mW]", None, QtGui.QApplication.UnicodeUTF8))
        self.exPowerAfterFilterLineEdit.setText(QtGui.QApplication.translate("MainWindow", "NaN", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "which objective?", None, QtGui.QApplication.UnicodeUTF8))
        self.whichObjectiveComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "i don\'t know...", None, QtGui.QApplication.UnicodeUTF8))
        self.whichObjectiveComboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "4x dry", None, QtGui.QApplication.UnicodeUTF8))
        self.whichObjectiveComboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "40x dry", None, QtGui.QApplication.UnicodeUTF8))
        self.whichObjectiveComboBox.setItemText(3, QtGui.QApplication.translate("MainWindow", "60x oil", None, QtGui.QApplication.UnicodeUTF8))
        self.whichObjectiveComboBox.setItemText(4, QtGui.QApplication.translate("MainWindow", "100x oil", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "NA", None, QtGui.QApplication.UnicodeUTF8))
        self.NALineEdit.setText(QtGui.QApplication.translate("MainWindow", "NaN", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Camera?", None, QtGui.QApplication.UnicodeUTF8))
        self.whichCameraComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "I forgot", None, QtGui.QApplication.UnicodeUTF8))
        self.whichCameraComboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "Cascade", None, QtGui.QApplication.UnicodeUTF8))
        self.whichCameraComboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "PhotonMax", None, QtGui.QApplication.UnicodeUTF8))
        self.whichCameraComboBox.setItemText(3, QtGui.QApplication.translate("MainWindow", "ProEm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Real gain?", None, QtGui.QApplication.UnicodeUTF8))
        self.realGainLineEdit.setText(QtGui.QApplication.translate("MainWindow", "NaN", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Optical element in excitation?", None, QtGui.QApplication.UnicodeUTF8))
        self.opticalElementInExcitationComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "L/2 plate", None, QtGui.QApplication.UnicodeUTF8))
        self.opticalElementInExcitationComboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "Polarizer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Artificial molecule:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "phase offset [deg]", None, QtGui.QApplication.UnicodeUTF8))
        self.phaseOffsetLineEdit.setText(QtGui.QApplication.translate("MainWindow", "NaN", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Isotropic emitter:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "modulation depth", None, QtGui.QApplication.UnicodeUTF8))
        self.modulationDepthLineEdit.setText(QtGui.QApplication.translate("MainWindow", "NaN", None, QtGui.QApplication.UnicodeUTF8))
        self.phaseLineEdit.setText(QtGui.QApplication.translate("MainWindow", "NaN", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "phase", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "user notes:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Conversion", None, QtGui.QApplication.UnicodeUTF8))
        self.convertPushButton.setText(QtGui.QApplication.translate("MainWindow", "All done?-- then convert!", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("MainWindow", "What kind of old data do you have?", None, QtGui.QApplication.UnicodeUTF8))
        self.whichSetupComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "old setup --- excitation motor detected with diode, emission motor digital", None, QtGui.QApplication.UnicodeUTF8))
        self.whichSetupComboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "new setup old style --- excitation continuous, emission stepwise", None, QtGui.QApplication.UnicodeUTF8))
        self.whichSetupComboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "new setup new style --- both excitation and emission stepwise", None, QtGui.QApplication.UnicodeUTF8))

