# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '2dgui.ui'
#
# Created: Thu May 23 11:57:09 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from mymplcanvas import MyMplCanvas
from matplotlib.backends.backend_qt4agg import NavigationToolbar2QTAgg as NavigationToolbar

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1309, 973)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 261, 121))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setStyleSheet(_fromUtf8(""))
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.selectSPEComboBox = QtGui.QComboBox(self.groupBox)
        self.selectSPEComboBox.setObjectName(_fromUtf8("selectSPEComboBox"))
        self.gridLayout.addWidget(self.selectSPEComboBox, 3, 0, 1, 2)
        self.selectDataDirPushButton = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectDataDirPushButton.sizePolicy().hasHeightForWidth())
        self.selectDataDirPushButton.setSizePolicy(sizePolicy)
        self.selectDataDirPushButton.setMinimumSize(QtCore.QSize(101, 27))
        self.selectDataDirPushButton.setBaseSize(QtCore.QSize(0, 0))
        self.selectDataDirPushButton.setObjectName(_fromUtf8("selectDataDirPushButton"))
        self.gridLayout.addWidget(self.selectDataDirPushButton, 0, 0, 1, 2)
        self.dataDirLabel = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.dataDirLabel.setFont(font)
        self.dataDirLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dataDirLabel.setText(_fromUtf8(""))
        self.dataDirLabel.setScaledContents(True)
        self.dataDirLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.dataDirLabel.setWordWrap(True)
        self.dataDirLabel.setObjectName(_fromUtf8("dataDirLabel"))
        self.gridLayout.addWidget(self.dataDirLabel, 1, 0, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout)
        self.imageview = MyMplCanvas(self.centralwidget, width=2, height=2, dpi=75)
        self.imageview.setGeometry(QtCore.QRect(10, 240, 641, 641))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.imageview.setFont(font)
        self.imageview.setFocusPolicy(QtCore.Qt.NoFocus)
        self.imageview.setObjectName(_fromUtf8("imageview"))
        self.dataview = MyMplCanvas(self.centralwidget, width=2, height=2, dpi=75)
        self.dataview.setGeometry(QtCore.QRect(660, 240, 641, 641))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.dataview.setFont(font)
        self.dataview.setObjectName(_fromUtf8("dataview"))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(290, 10, 401, 201))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setStyleSheet(_fromUtf8(""))
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setContentsMargins(8, -1, 8, -1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.clearAllSpotsPushButton = QtGui.QPushButton(self.groupBox_2)
        self.clearAllSpotsPushButton.setMinimumSize(QtCore.QSize(101, 27))
        self.clearAllSpotsPushButton.setObjectName(_fromUtf8("clearAllSpotsPushButton"))
        self.gridLayout_2.addWidget(self.clearAllSpotsPushButton, 7, 2, 1, 1)
        self.setBGSpotPushButton = QtGui.QPushButton(self.groupBox_2)
        self.setBGSpotPushButton.setMinimumSize(QtCore.QSize(101, 27))
        self.setBGSpotPushButton.setObjectName(_fromUtf8("setBGSpotPushButton"))
        self.gridLayout_2.addWidget(self.setBGSpotPushButton, 3, 0, 1, 1)
        self.addSMPushButton = QtGui.QPushButton(self.groupBox_2)
        self.addSMPushButton.setObjectName(_fromUtf8("addSMPushButton"))
        self.gridLayout_2.addWidget(self.addSMPushButton, 4, 0, 1, 1)
        self.createSpotArrayPushButton = QtGui.QPushButton(self.groupBox_2)
        self.createSpotArrayPushButton.setMinimumSize(QtCore.QSize(101, 27))
        self.createSpotArrayPushButton.setCheckable(False)
        self.createSpotArrayPushButton.setObjectName(_fromUtf8("createSpotArrayPushButton"))
        self.gridLayout_2.addWidget(self.createSpotArrayPushButton, 6, 0, 1, 1)
        self.importSpotCoordsPushButton = QtGui.QPushButton(self.groupBox_2)
        self.importSpotCoordsPushButton.setObjectName(_fromUtf8("importSpotCoordsPushButton"))
        self.gridLayout_2.addWidget(self.importSpotCoordsPushButton, 5, 0, 1, 1)
        self.spotTypeComboBox = QtGui.QComboBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spotTypeComboBox.setFont(font)
        self.spotTypeComboBox.setObjectName(_fromUtf8("spotTypeComboBox"))
        self.spotTypeComboBox.addItem(_fromUtf8(""))
        self.spotTypeComboBox.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.spotTypeComboBox, 4, 2, 1, 1)
        self.addSignalSpotPushButton = QtGui.QPushButton(self.groupBox_2)
        self.addSignalSpotPushButton.setMinimumSize(QtCore.QSize(101, 27))
        self.addSignalSpotPushButton.setObjectName(_fromUtf8("addSignalSpotPushButton"))
        self.gridLayout_2.addWidget(self.addSignalSpotPushButton, 3, 1, 1, 2)
        self.phaseOffsetLabel_6 = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.phaseOffsetLabel_6.setFont(font)
        self.phaseOffsetLabel_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.phaseOffsetLabel_6.setAlignment(QtCore.Qt.AlignCenter)
        self.phaseOffsetLabel_6.setObjectName(_fromUtf8("phaseOffsetLabel_6"))
        self.gridLayout_2.addWidget(self.phaseOffsetLabel_6, 4, 1, 1, 1)
        self.spotAttributeLabel = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.spotAttributeLabel.setFont(font)
        self.spotAttributeLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.spotAttributeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.spotAttributeLabel.setObjectName(_fromUtf8("spotAttributeLabel"))
        self.gridLayout_2.addWidget(self.spotAttributeLabel, 5, 1, 1, 1)
        self.useExSpotCheckBox = QtGui.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.useExSpotCheckBox.setFont(font)
        self.useExSpotCheckBox.setObjectName(_fromUtf8("useExSpotCheckBox"))
        self.gridLayout_2.addWidget(self.useExSpotCheckBox, 6, 1, 1, 1)
        self.spotEdgeLengthSpinBox = QtGui.QSpinBox(self.groupBox_2)
        self.spotEdgeLengthSpinBox.setProperty("value", 6)
        self.spotEdgeLengthSpinBox.setObjectName(_fromUtf8("spotEdgeLengthSpinBox"))
        self.gridLayout_2.addWidget(self.spotEdgeLengthSpinBox, 5, 2, 1, 1)
        self.useBorderBGCheckBox = QtGui.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.useBorderBGCheckBox.setFont(font)
        self.useBorderBGCheckBox.setChecked(True)
        self.useBorderBGCheckBox.setObjectName(_fromUtf8("useBorderBGCheckBox"))
        self.gridLayout_2.addWidget(self.useBorderBGCheckBox, 6, 2, 1, 1)
        self.clearSpotPushButton = QtGui.QPushButton(self.groupBox_2)
        self.clearSpotPushButton.setMinimumSize(QtCore.QSize(101, 27))
        self.clearSpotPushButton.setObjectName(_fromUtf8("clearSpotPushButton"))
        self.gridLayout_2.addWidget(self.clearSpotPushButton, 7, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(690, 10, 351, 201))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setStyleSheet(_fromUtf8(""))
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setCheckable(False)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setContentsMargins(8, -1, 8, -1)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.corrMDoubleSpinBox = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.corrMDoubleSpinBox.setMaximum(1.0)
        self.corrMDoubleSpinBox.setSingleStep(0.1)
        self.corrMDoubleSpinBox.setObjectName(_fromUtf8("corrMDoubleSpinBox"))
        self.gridLayout_3.addWidget(self.corrMDoubleSpinBox, 1, 1, 1, 1)
        self.SNRSpinBox = QtGui.QSpinBox(self.groupBox_3)
        self.SNRSpinBox.setProperty("value", 10)
        self.SNRSpinBox.setObjectName(_fromUtf8("SNRSpinBox"))
        self.gridLayout_3.addWidget(self.SNRSpinBox, 0, 1, 1, 1)
        self.cosineFitPushButton = QtGui.QPushButton(self.groupBox_3)
        self.cosineFitPushButton.setMinimumSize(QtCore.QSize(101, 27))
        self.cosineFitPushButton.setCheckable(False)
        self.cosineFitPushButton.setObjectName(_fromUtf8("cosineFitPushButton"))
        self.gridLayout_3.addWidget(self.cosineFitPushButton, 2, 0, 1, 1)
        self.testPushButton = QtGui.QPushButton(self.groupBox_3)
        self.testPushButton.setMinimumSize(QtCore.QSize(101, 27))
        self.testPushButton.setCheckable(False)
        self.testPushButton.setObjectName(_fromUtf8("testPushButton"))
        self.gridLayout_3.addWidget(self.testPushButton, 2, 2, 1, 1)
        self.corrMDoubleSpinBox_2 = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.corrMDoubleSpinBox_2.setMinimum(-1.57)
        self.corrMDoubleSpinBox_2.setMaximum(1.57)
        self.corrMDoubleSpinBox_2.setSingleStep(0.1)
        self.corrMDoubleSpinBox_2.setObjectName(_fromUtf8("corrMDoubleSpinBox_2"))
        self.gridLayout_3.addWidget(self.corrMDoubleSpinBox_2, 1, 2, 1, 1)
        self.findModDepthsPushButton = QtGui.QPushButton(self.groupBox_3)
        self.findModDepthsPushButton.setMinimumSize(QtCore.QSize(101, 27))
        self.findModDepthsPushButton.setCheckable(False)
        self.findModDepthsPushButton.setObjectName(_fromUtf8("findModDepthsPushButton"))
        self.gridLayout_3.addWidget(self.findModDepthsPushButton, 2, 1, 1, 1)
        self.checkSpotValidityPushButton = QtGui.QPushButton(self.groupBox_3)
        self.checkSpotValidityPushButton.setMinimumSize(QtCore.QSize(101, 27))
        self.checkSpotValidityPushButton.setCheckable(False)
        self.checkSpotValidityPushButton.setObjectName(_fromUtf8("checkSpotValidityPushButton"))
        self.gridLayout_3.addWidget(self.checkSpotValidityPushButton, 0, 2, 1, 1)
        self.phaseOffsetLabel_4 = QtGui.QLabel(self.groupBox_3)
        self.phaseOffsetLabel_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.phaseOffsetLabel_4.setAlignment(QtCore.Qt.AlignCenter)
        self.phaseOffsetLabel_4.setObjectName(_fromUtf8("phaseOffsetLabel_4"))
        self.gridLayout_3.addWidget(self.phaseOffsetLabel_4, 1, 0, 1, 1)
        self.clearAllSpotsPushButton_4 = QtGui.QPushButton(self.groupBox_3)
        self.clearAllSpotsPushButton_4.setEnabled(False)
        self.clearAllSpotsPushButton_4.setMinimumSize(QtCore.QSize(101, 27))
        self.clearAllSpotsPushButton_4.setObjectName(_fromUtf8("clearAllSpotsPushButton_4"))
        self.gridLayout_3.addWidget(self.clearAllSpotsPushButton_4, 3, 2, 1, 1)
        self.ETrulerPushButton = QtGui.QPushButton(self.groupBox_3)
        self.ETrulerPushButton.setMinimumSize(QtCore.QSize(101, 27))
        self.ETrulerPushButton.setCheckable(False)
        self.ETrulerPushButton.setObjectName(_fromUtf8("ETrulerPushButton"))
        self.gridLayout_3.addWidget(self.ETrulerPushButton, 3, 1, 1, 1)
        self.phaseOffsetLabel_3 = QtGui.QLabel(self.groupBox_3)
        self.phaseOffsetLabel_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.phaseOffsetLabel_3.setAlignment(QtCore.Qt.AlignCenter)
        self.phaseOffsetLabel_3.setObjectName(_fromUtf8("phaseOffsetLabel_3"))
        self.gridLayout_3.addWidget(self.phaseOffsetLabel_3, 0, 0, 1, 1)
        self.saveContrastImagesPushButton = QtGui.QPushButton(self.groupBox_3)
        self.saveContrastImagesPushButton.setMinimumSize(QtCore.QSize(101, 27))
        self.saveContrastImagesPushButton.setCheckable(False)
        self.saveContrastImagesPushButton.setObjectName(_fromUtf8("saveContrastImagesPushButton"))
        self.gridLayout_3.addWidget(self.saveContrastImagesPushButton, 3, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(1040, 10, 271, 201))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setStyleSheet(_fromUtf8(""))
        self.groupBox_4.setFlat(False)
        self.groupBox_4.setCheckable(False)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setContentsMargins(8, -1, 8, -1)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.spotInfoTextBrowser = QtGui.QTextBrowser(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Mono"))
        font.setPointSize(9)
        self.spotInfoTextBrowser.setFont(font)
        self.spotInfoTextBrowser.setObjectName(_fromUtf8("spotInfoTextBrowser"))
        self.gridLayout_4.addWidget(self.spotInfoTextBrowser, 0, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_4)
        self.showWhatComboBox = QtGui.QComboBox(self.centralwidget)
        self.showWhatComboBox.setGeometry(QtCore.QRect(1190, 240, 111, 27))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.showWhatComboBox.setFont(font)
        self.showWhatComboBox.setObjectName(_fromUtf8("showWhatComboBox"))
        self.showWhatComboBox.addItem(_fromUtf8(""))
        self.showWhatComboBox.addItem(_fromUtf8(""))
        self.showWhatComboBox.addItem(_fromUtf8(""))
        self.showWhatComboBox.addItem(_fromUtf8(""))
        self.imageview_navbar = NavigationToolbar(self.imageview, self.centralwidget)
        self.imageview_navbar.setGeometry(QtCore.QRect(10, 880, 641, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.imageview_navbar.setFont(font)
        self.imageview_navbar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.imageview_navbar.setObjectName(_fromUtf8("imageview_navbar"))
        self.dataview_navbar = NavigationToolbar(self.dataview, self.centralwidget)
        self.dataview_navbar.setGeometry(QtCore.QRect(660, 880, 641, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.dataview_navbar.setFont(font)
        self.dataview_navbar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dataview_navbar.setObjectName(_fromUtf8("dataview_navbar"))
        self.showStuffComboBox = QtGui.QComboBox(self.centralwidget)
        self.showStuffComboBox.setGeometry(QtCore.QRect(580, 240, 71, 27))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.showStuffComboBox.setFont(font)
        self.showStuffComboBox.setObjectName(_fromUtf8("showStuffComboBox"))
        self.showStuffComboBox.addItem(_fromUtf8(""))
        self.showStuffComboBox.addItem(_fromUtf8(""))
        self.showStuffComboBox.addItem(_fromUtf8(""))
        self.showStuffComboBox.addItem(_fromUtf8(""))
        self.showStuffComboBox.addItem(_fromUtf8(""))
        self.showStuffComboBox.addItem(_fromUtf8(""))
        self.showStuffComboBox.addItem(_fromUtf8(""))
        self.showStuffComboBox.addItem(_fromUtf8(""))
        self.showWhatDataComboBox = QtGui.QComboBox(self.centralwidget)
        self.showWhatDataComboBox.setGeometry(QtCore.QRect(10, 240, 191, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.showWhatDataComboBox.setFont(font)
        self.showWhatDataComboBox.setObjectName(_fromUtf8("showWhatDataComboBox"))
        self.showWhatDataComboBox.addItem(_fromUtf8(""))
        self.showWhatDataComboBox.addItem(_fromUtf8(""))
        self.showWhatDataComboBox.addItem(_fromUtf8(""))
        self.showWhatDataComboBox.addItem(_fromUtf8(""))
        self.showWhatDataComboBox.addItem(_fromUtf8(""))
        self.showWhatDataComboBox.addItem(_fromUtf8(""))
        self.showWhatDataComboBox.addItem(_fromUtf8(""))
        self.showWhatDataComboBox.setItemText(6, _fromUtf8(""))
        self.groupBox_5 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 130, 261, 71))
        self.groupBox_5.setAutoFillBackground(True)
        self.groupBox_5.setFlat(False)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.moveSpotRightPushButton = QtGui.QPushButton(self.groupBox_5)
        self.moveSpotRightPushButton.setGeometry(QtCore.QRect(210, 30, 21, 22))
        self.moveSpotRightPushButton.setObjectName(_fromUtf8("moveSpotRightPushButton"))
        self.moveSpotUpPushButton = QtGui.QPushButton(self.groupBox_5)
        self.moveSpotUpPushButton.setGeometry(QtCore.QRect(190, 20, 21, 22))
        self.moveSpotUpPushButton.setObjectName(_fromUtf8("moveSpotUpPushButton"))
        self.moveSpotLeftPushButton = QtGui.QPushButton(self.groupBox_5)
        self.moveSpotLeftPushButton.setGeometry(QtCore.QRect(170, 30, 21, 22))
        self.moveSpotLeftPushButton.setObjectName(_fromUtf8("moveSpotLeftPushButton"))
        self.moveSpotDownPushButton = QtGui.QPushButton(self.groupBox_5)
        self.moveSpotDownPushButton.setGeometry(QtCore.QRect(190, 40, 21, 22))
        self.moveSpotDownPushButton.setObjectName(_fromUtf8("moveSpotDownPushButton"))
        self.selectLastDataDirPushButton = QtGui.QPushButton(self.groupBox_5)
        self.selectLastDataDirPushButton.setGeometry(QtCore.QRect(20, 30, 91, 22))
        self.selectLastDataDirPushButton.setObjectName(_fromUtf8("selectLastDataDirPushButton"))
        self.phaseOffsetLabel_5 = QtGui.QLabel(self.groupBox_5)
        self.phaseOffsetLabel_5.setGeometry(QtCore.QRect(164, 0, 71, 27))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.phaseOffsetLabel_5.setFont(font)
        self.phaseOffsetLabel_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.phaseOffsetLabel_5.setAlignment(QtCore.Qt.AlignCenter)
        self.phaseOffsetLabel_5.setObjectName(_fromUtf8("phaseOffsetLabel_5"))
        self.frameSlider = QtGui.QSlider(self.centralwidget)
        self.frameSlider.setGeometry(QtCore.QRect(10, 850, 641, 29))
        self.frameSlider.setOrientation(QtCore.Qt.Horizontal)
        self.frameSlider.setObjectName(_fromUtf8("frameSlider"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Data import and basic parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.selectDataDirPushButton.setText(QtGui.QApplication.translate("MainWindow", "select data directory", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Spot helper", None, QtGui.QApplication.UnicodeUTF8))
        self.clearAllSpotsPushButton.setText(QtGui.QApplication.translate("MainWindow", "clear all", None, QtGui.QApplication.UnicodeUTF8))
        self.setBGSpotPushButton.setText(QtGui.QApplication.translate("MainWindow", "set BG spot", None, QtGui.QApplication.UnicodeUTF8))
        self.addSMPushButton.setText(QtGui.QApplication.translate("MainWindow", "add sm", None, QtGui.QApplication.UnicodeUTF8))
        self.createSpotArrayPushButton.setText(QtGui.QApplication.translate("MainWindow", "create array", None, QtGui.QApplication.UnicodeUTF8))
        self.importSpotCoordsPushButton.setText(QtGui.QApplication.translate("MainWindow", "import", None, QtGui.QApplication.UnicodeUTF8))
        self.spotTypeComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "square", None, QtGui.QApplication.UnicodeUTF8))
        self.spotTypeComboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "circle", None, QtGui.QApplication.UnicodeUTF8))
        self.addSignalSpotPushButton.setText(QtGui.QApplication.translate("MainWindow", "add spot from selection", None, QtGui.QApplication.UnicodeUTF8))
        self.phaseOffsetLabel_6.setText(QtGui.QApplication.translate("MainWindow", "shape:", None, QtGui.QApplication.UnicodeUTF8))
        self.spotAttributeLabel.setText(QtGui.QApplication.translate("MainWindow", "edge length:", None, QtGui.QApplication.UnicodeUTF8))
        self.useExSpotCheckBox.setText(QtGui.QApplication.translate("MainWindow", "use excitation spot", None, QtGui.QApplication.UnicodeUTF8))
        self.useBorderBGCheckBox.setText(QtGui.QApplication.translate("MainWindow", "use border bg", None, QtGui.QApplication.UnicodeUTF8))
        self.clearSpotPushButton.setText(QtGui.QApplication.translate("MainWindow", "clear spot", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Analysis tools", None, QtGui.QApplication.UnicodeUTF8))
        self.cosineFitPushButton.setText(QtGui.QApplication.translate("MainWindow", "cos fit", None, QtGui.QApplication.UnicodeUTF8))
        self.testPushButton.setText(QtGui.QApplication.translate("MainWindow", "test", None, QtGui.QApplication.UnicodeUTF8))
        self.findModDepthsPushButton.setText(QtGui.QApplication.translate("MainWindow", "find M + ph", None, QtGui.QApplication.UnicodeUTF8))
        self.checkSpotValidityPushButton.setText(QtGui.QApplication.translate("MainWindow", "check", None, QtGui.QApplication.UnicodeUTF8))
        self.phaseOffsetLabel_4.setText(QtGui.QApplication.translate("MainWindow", "emission corr", None, QtGui.QApplication.UnicodeUTF8))
        self.clearAllSpotsPushButton_4.setText(QtGui.QApplication.translate("MainWindow", "ET model", None, QtGui.QApplication.UnicodeUTF8))
        self.ETrulerPushButton.setText(QtGui.QApplication.translate("MainWindow", "ET ruler", None, QtGui.QApplication.UnicodeUTF8))
        self.phaseOffsetLabel_3.setText(QtGui.QApplication.translate("MainWindow", "SNR limit", None, QtGui.QApplication.UnicodeUTF8))
        self.saveContrastImagesPushButton.setText(QtGui.QApplication.translate("MainWindow", "save images", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("MainWindow", "Spot info", None, QtGui.QApplication.UnicodeUTF8))
        self.showWhatComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "intensity trace", None, QtGui.QApplication.UnicodeUTF8))
        self.showWhatComboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "portrait data", None, QtGui.QApplication.UnicodeUTF8))
        self.showWhatComboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "portrait fit", None, QtGui.QApplication.UnicodeUTF8))
        self.showWhatComboBox.setItemText(3, QtGui.QApplication.translate("MainWindow", "portrait residual", None, QtGui.QApplication.UnicodeUTF8))
        self.showStuffComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "spots", None, QtGui.QApplication.UnicodeUTF8))
        self.showStuffComboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "M_ex", None, QtGui.QApplication.UnicodeUTF8))
        self.showStuffComboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "M_em", None, QtGui.QApplication.UnicodeUTF8))
        self.showStuffComboBox.setItemText(3, QtGui.QApplication.translate("MainWindow", "phase_ex", None, QtGui.QApplication.UnicodeUTF8))
        self.showStuffComboBox.setItemText(4, QtGui.QApplication.translate("MainWindow", "phase_em", None, QtGui.QApplication.UnicodeUTF8))
        self.showStuffComboBox.setItemText(5, QtGui.QApplication.translate("MainWindow", "r", None, QtGui.QApplication.UnicodeUTF8))
        self.showStuffComboBox.setItemText(6, QtGui.QApplication.translate("MainWindow", "SNR", None, QtGui.QApplication.UnicodeUTF8))
        self.showStuffComboBox.setItemText(7, QtGui.QApplication.translate("MainWindow", "ET_ruler", None, QtGui.QApplication.UnicodeUTF8))
        self.showWhatDataComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "sample", None, QtGui.QApplication.UnicodeUTF8))
        self.showWhatDataComboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "blank", None, QtGui.QApplication.UnicodeUTF8))
        self.showWhatDataComboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "laser", None, QtGui.QApplication.UnicodeUTF8))
        self.showWhatDataComboBox.setItemText(3, QtGui.QApplication.translate("MainWindow", "sample-bg", None, QtGui.QApplication.UnicodeUTF8))
        self.showWhatDataComboBox.setItemText(4, QtGui.QApplication.translate("MainWindow", "sample-bg-(blank-bg)", None, QtGui.QApplication.UnicodeUTF8))
        self.showWhatDataComboBox.setItemText(5, QtGui.QApplication.translate("MainWindow", "(sample-bg-(blank-bg))/(laser-bg)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("MainWindow", "aux tools", None, QtGui.QApplication.UnicodeUTF8))
        self.moveSpotRightPushButton.setText(QtGui.QApplication.translate("MainWindow", ">", None, QtGui.QApplication.UnicodeUTF8))
        self.moveSpotUpPushButton.setText(QtGui.QApplication.translate("MainWindow", "^", None, QtGui.QApplication.UnicodeUTF8))
        self.moveSpotLeftPushButton.setText(QtGui.QApplication.translate("MainWindow", "<", None, QtGui.QApplication.UnicodeUTF8))
        self.moveSpotDownPushButton.setText(QtGui.QApplication.translate("MainWindow", "v", None, QtGui.QApplication.UnicodeUTF8))
        self.selectLastDataDirPushButton.setText(QtGui.QApplication.translate("MainWindow", "load default", None, QtGui.QApplication.UnicodeUTF8))
        self.phaseOffsetLabel_5.setText(QtGui.QApplication.translate("MainWindow", "move spot", None, QtGui.QApplication.UnicodeUTF8))

